/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ProdutosDAO;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import model.Produtos;

/**
 *
 * @author caio
 */
public class ViewVendas extends javax.swing.JFrame {
    
    double total,preco,subtotal;
    int qnt;
    
    DefaultTableModel carrinho;
    /**
     * Creates new form ViewClientes
     */   
    
    public ViewVendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Pregistradordeprodutos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Bconsultapordata = new javax.swing.JButton();
        Bhistoricodevendas = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        LABELcpf = new javax.swing.JLabel();
        LABELdatadavenda = new javax.swing.JLabel();
        TXTdatadavenda = new javax.swing.JTextField();
        LABELnome = new javax.swing.JLabel();
        TXTnome = new javax.swing.JTextField();
        TXTcelular = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        LABELcodigo = new javax.swing.JLabel();
        TXTid = new javax.swing.JTextField();
        Bpesquisa = new javax.swing.JButton();
        LABELproduto = new javax.swing.JLabel();
        TXTproduto = new javax.swing.JTextField();
        LABELqnt = new javax.swing.JLabel();
        TXTqnt = new javax.swing.JTextField();
        LABELpreco = new javax.swing.JLabel();
        TXTpreco = new javax.swing.JTextField();
        Badicionar = new javax.swing.JButton();
        LABELproduto1 = new javax.swing.JLabel();
        TXTcor = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        LABELtotal = new javax.swing.JLabel();
        TXTtotal = new javax.swing.JTextField();
        Bpagar = new javax.swing.JButton();
        Bcancelar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        TABcarrinho = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LABELcarrinho = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PONTO DE VENDAS - SilhuettaSystem");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(236, 230, 230));

        Pregistradordeprodutos.setBackground(new java.awt.Color(174, 144, 84));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logo-Sullhueta-BRANCO.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/VENDASBRANCO.png"))); // NOI18N
        jLabel2.setText("PONTO DE VENDAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        Bconsultapordata.setBackground(new java.awt.Color(174, 144, 84));
        Bconsultapordata.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Bconsultapordata.setForeground(new java.awt.Color(255, 255, 255));
        Bconsultapordata.setText("Consulta por Data >");
        Bconsultapordata.setBorderPainted(false);
        Bconsultapordata.setContentAreaFilled(false);
        Bconsultapordata.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Bconsultapordata.setHideActionText(true);
        Bconsultapordata.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Bconsultapordata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BconsultapordataMouseClicked(evt);
            }
        });
        Bconsultapordata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BconsultapordataActionPerformed(evt);
            }
        });

        Bhistoricodevendas.setBackground(new java.awt.Color(174, 144, 84));
        Bhistoricodevendas.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Bhistoricodevendas.setForeground(new java.awt.Color(255, 255, 255));
        Bhistoricodevendas.setText("Histórico de Vendas >");
        Bhistoricodevendas.setBorderPainted(false);
        Bhistoricodevendas.setContentAreaFilled(false);
        Bhistoricodevendas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Bhistoricodevendas.setHideActionText(true);
        Bhistoricodevendas.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        Bhistoricodevendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BhistoricodevendasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PregistradordeprodutosLayout = new javax.swing.GroupLayout(Pregistradordeprodutos);
        Pregistradordeprodutos.setLayout(PregistradordeprodutosLayout);
        PregistradordeprodutosLayout.setHorizontalGroup(
            PregistradordeprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PregistradordeprodutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PregistradordeprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Bhistoricodevendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bconsultapordata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(188, 188, 188)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        PregistradordeprodutosLayout.setVerticalGroup(
            PregistradordeprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PregistradordeprodutosLayout.createSequentialGroup()
                .addGroup(PregistradordeprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PregistradordeprodutosLayout.createSequentialGroup()
                        .addComponent(Bconsultapordata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bhistoricodevendas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(200, 193, 189));

        LABELcpf.setForeground(new java.awt.Color(0, 0, 0));
        LABELcpf.setText("Telefone:");

        LABELdatadavenda.setForeground(new java.awt.Color(0, 0, 0));
        LABELdatadavenda.setText("Data:");

        TXTdatadavenda.setEditable(false);
        TXTdatadavenda.setBackground(new java.awt.Color(255, 255, 255));
        TXTdatadavenda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTdatadavenda.setForeground(new java.awt.Color(0, 0, 0));

        LABELnome.setForeground(new java.awt.Color(0, 0, 0));
        LABELnome.setText("Nome:");

        TXTnome.setBackground(new java.awt.Color(255, 255, 255));
        TXTnome.setForeground(new java.awt.Color(0, 0, 0));

        TXTcelular.setBackground(new java.awt.Color(255, 255, 255));
        TXTcelular.setForeground(new java.awt.Color(0, 0, 0));
        try {
            TXTcelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TXTcelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTcelularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LABELnome)
                    .addComponent(LABELcpf))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TXTcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(LABELdatadavenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTdatadavenda))
                    .addComponent(TXTnome))
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABELnome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELdatadavenda)
                    .addComponent(TXTdatadavenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTcelular)
                    .addComponent(LABELcpf))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        LABELcodigo.setForeground(new java.awt.Color(0, 0, 0));
        LABELcodigo.setText("ID do Produto:");

        TXTid.setBackground(new java.awt.Color(242, 242, 242));
        TXTid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTid.setForeground(new java.awt.Color(0, 0, 0));

        Bpesquisa.setBackground(new java.awt.Color(195, 195, 195));
        Bpesquisa.setForeground(new java.awt.Color(0, 0, 0));
        Bpesquisa.setText("Pesquisa");
        Bpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpesquisaActionPerformed(evt);
            }
        });

        LABELproduto.setForeground(new java.awt.Color(0, 0, 0));
        LABELproduto.setText("Produto:");

        TXTproduto.setEditable(false);
        TXTproduto.setBackground(new java.awt.Color(197, 205, 222));
        TXTproduto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTproduto.setForeground(new java.awt.Color(0, 0, 0));

        LABELqnt.setForeground(new java.awt.Color(0, 0, 0));
        LABELqnt.setText("Qnt:");

        TXTqnt.setBackground(new java.awt.Color(242, 242, 242));
        TXTqnt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTqnt.setForeground(new java.awt.Color(0, 0, 0));

        LABELpreco.setForeground(new java.awt.Color(0, 0, 0));
        LABELpreco.setText("Preço Unit:");

        TXTpreco.setEditable(false);
        TXTpreco.setBackground(new java.awt.Color(197, 205, 222));
        TXTpreco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTpreco.setForeground(new java.awt.Color(0, 0, 102));
        TXTpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTprecoActionPerformed(evt);
            }
        });

        Badicionar.setBackground(new java.awt.Color(195, 195, 195));
        Badicionar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Badicionar.setForeground(new java.awt.Color(0, 0, 0));
        Badicionar.setText("Adicionar Itens");
        Badicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BadicionarActionPerformed(evt);
            }
        });

        LABELproduto1.setForeground(new java.awt.Color(0, 0, 0));
        LABELproduto1.setText("Cor:");

        TXTcor.setEditable(false);
        TXTcor.setBackground(new java.awt.Color(197, 205, 222));
        TXTcor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTcor.setForeground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LABELcodigo)
                    .addComponent(LABELproduto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LABELproduto1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Badicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(TXTcor, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LABELpreco)
                            .addComponent(LABELqnt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TXTpreco, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(TXTqnt)))
                    .addComponent(TXTproduto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(TXTid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bpesquisa)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABELproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTcor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABELpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABELproduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELqnt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTqnt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(Badicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(160, 133, 83));

        LABELtotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LABELtotal.setForeground(new java.awt.Color(0, 0, 0));
        LABELtotal.setText("TOTAL (R$):");

        TXTtotal.setEditable(false);
        TXTtotal.setBackground(new java.awt.Color(255, 255, 255));
        TXTtotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTtotal.setForeground(new java.awt.Color(0, 51, 102));

        Bpagar.setBackground(new java.awt.Color(195, 195, 195));
        Bpagar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Bpagar.setForeground(new java.awt.Color(0, 0, 0));
        Bpagar.setText("Pagar");
        Bpagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpagarActionPerformed(evt);
            }
        });

        Bcancelar.setBackground(new java.awt.Color(195, 195, 195));
        Bcancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Bcancelar.setForeground(new java.awt.Color(204, 0, 0));
        Bcancelar.setText("Cancelar");
        Bcancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BcancelarMouseClicked(evt);
            }
        });
        Bcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Bcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Bpagar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(LABELtotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TXTtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bpagar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Cor", "Quant", "Custo", "Subtotal"
            }
        ));
        jTable1.setEnabled(false);
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        TABcarrinho.setViewportView(jTable1);

        LABELcarrinho.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LABELcarrinho.setForeground(new java.awt.Color(102, 102, 102));
        LABELcarrinho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LABELcarrinho.setText("Carrinho:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TABcarrinho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(LABELcarrinho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LABELcarrinho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TABcarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pregistradordeprodutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Pregistradordeprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Date agora = new Date();
        SimpleDateFormat dataBr = new SimpleDateFormat("dd/MM/yyyy");
        String dataformatada = dataBr.format(agora);
        TXTdatadavenda.setText(dataformatada);
    }//GEN-LAST:event_formWindowActivated

    private void BpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpesquisaActionPerformed
        Produtos obj = new Produtos();
        ProdutosDAO dao = new ProdutosDAO();
        
        obj = dao.consultaProdutosPorId(Integer.valueOf(TXTid.getText()));
        
        TXTproduto.setText(obj.getModelo());
        TXTcor.setText(obj.getCor());
        TXTpreco.setText (String.valueOf(obj.getCusto()));
    }//GEN-LAST:event_BpesquisaActionPerformed

    private void BadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BadicionarActionPerformed
        qnt = Integer.parseInt(TXTqnt.getText());
        preco = Double.parseDouble(TXTpreco.getText());
        
        subtotal = qnt*preco;
        
        total += subtotal; 
        TXTtotal.setText(String.valueOf(total));
        
        //carrinho:
        carrinho = (DefaultTableModel) jTable1.getModel();
        
        carrinho.addRow(new Object[]{

            TXTid.getText(),
            TXTproduto.getText(),
            TXTcor.getText(),
            TXTqnt.getText(),
            TXTpreco.getText(),
            subtotal
        });
    }//GEN-LAST:event_BadicionarActionPerformed

    private void BpagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpagarActionPerformed
        ViewPagamentos telapagamentos = new ViewPagamentos();
        telapagamentos.TXTtotal.setText(String.valueOf(total));
        
        telapagamentos.carrinho = carrinho;
        
        telapagamentos.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_BpagarActionPerformed

    private void BcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcancelarActionPerformed
         this.dispose();
    }//GEN-LAST:event_BcancelarActionPerformed

    private void BcancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BcancelarMouseClicked
        
    }//GEN-LAST:event_BcancelarMouseClicked

    private void BconsultapordataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BconsultapordataActionPerformed
        ViewTotalVendasPorData tela = new ViewTotalVendasPorData();
        tela.setVisible(true);
    }//GEN-LAST:event_BconsultapordataActionPerformed

    private void BhistoricodevendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BhistoricodevendasActionPerformed
        ViewHistoricoVendas tela = new ViewHistoricoVendas();
        tela.setVisible(true);
    }//GEN-LAST:event_BhistoricodevendasActionPerformed

    private void BconsultapordataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BconsultapordataMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BconsultapordataMouseClicked

    private void TXTcelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTcelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTcelularActionPerformed

    private void TXTprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTprecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTprecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Badicionar;
    private javax.swing.JButton Bcancelar;
    private javax.swing.JButton Bconsultapordata;
    private javax.swing.JButton Bhistoricodevendas;
    private javax.swing.JButton Bpagar;
    private javax.swing.JButton Bpesquisa;
    private javax.swing.JLabel LABELcarrinho;
    private javax.swing.JLabel LABELcodigo;
    private javax.swing.JLabel LABELcpf;
    private javax.swing.JLabel LABELdatadavenda;
    private javax.swing.JLabel LABELnome;
    private javax.swing.JLabel LABELpreco;
    private javax.swing.JLabel LABELproduto;
    private javax.swing.JLabel LABELproduto1;
    private javax.swing.JLabel LABELqnt;
    private javax.swing.JLabel LABELtotal;
    private javax.swing.JPanel Pregistradordeprodutos;
    private javax.swing.JScrollPane TABcarrinho;
    private javax.swing.JFormattedTextField TXTcelular;
    private javax.swing.JTextField TXTcor;
    private javax.swing.JTextField TXTdatadavenda;
    private javax.swing.JTextField TXTid;
    private javax.swing.JTextField TXTnome;
    private javax.swing.JTextField TXTpreco;
    private javax.swing.JTextField TXTproduto;
    private javax.swing.JTextField TXTqnt;
    private javax.swing.JTextField TXTtotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
