/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ProdutosDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Produtos;
import model.Utilitarios;

/**
 *
 * @author caio
 */
public class ViewProdutos extends javax.swing.JFrame {

    /**
     * Creates new form ViewClientes
     */
    
    public void listar(){
        
        ProdutosDAO dao = new ProdutosDAO();
        List<Produtos> lista = dao.listarProdutos();
        DefaultTableModel dados = (DefaultTableModel) TABprodutos.getModel();
        dados.setNumRows(0);
        
        for (Produtos p: lista){
            dados.addRow(new Object[]{
                p.getId(),
                p.getCodigo(),        
                p.getReferencia(),
                p.getCusto(),
                p.getQuantidade(),
                p.getFornecedor(),
                p.getModelo(),
                p.getTipo(),
                p.getTamanho(),
                p.getCor(),
                        
        });
        }
    }
    
    public ViewProdutos() {
        initComponents();
        TXTpesquisarref.setText("0");
        TXTpesquisartam.setText("0");
        TXTpesquisarmod.setText("0");
        TXTpesquisarcor.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Pregistradordeprodutos = new javax.swing.JPanel();
        Lregistradordeprodutos = new javax.swing.JLabel();
        Bconsultaestoque = new javax.swing.JButton();
        Bexcluir = new javax.swing.JButton();
        Bnovo = new javax.swing.JButton();
        Balterar = new javax.swing.JButton();
        Bsalvar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PAINELcadastrarclientes = new javax.swing.JPanel();
        LABELcodigo = new javax.swing.JLabel();
        TXTcodigo = new javax.swing.JTextField();
        LABELmodelo = new javax.swing.JLabel();
        TXTmodelo = new javax.swing.JTextField();
        LABELreferencia = new javax.swing.JLabel();
        TXTreferencia = new javax.swing.JTextField();
        LABELfornecedor = new javax.swing.JLabel();
        LABELtipo = new javax.swing.JLabel();
        TXTtipo = new javax.swing.JTextField();
        TXTcor = new javax.swing.JTextField();
        LABELcor = new javax.swing.JLabel();
        LABELtamanho = new javax.swing.JLabel();
        TXTtamanho = new javax.swing.JTextField();
        LABELcusto = new javax.swing.JLabel();
        TXTcusto = new javax.swing.JTextField();
        LABELquantidade = new javax.swing.JLabel();
        TXTquantidade = new javax.swing.JTextField();
        TXTfornecedor = new javax.swing.JTextField();
        LABELcodigo1 = new javax.swing.JLabel();
        TXTbuscaid = new javax.swing.JTextField();
        Bbuscar = new javax.swing.JButton();
        LABELcodigo2 = new javax.swing.JLabel();
        TXTid = new javax.swing.JTextField();
        PAINELprocurarprodutos = new javax.swing.JPanel();
        PAINELprodutos = new javax.swing.JScrollPane();
        TABprodutos = new javax.swing.JTable();
        LABELpesquisarref = new javax.swing.JLabel();
        TXTpesquisarref = new javax.swing.JTextField();
        Bfiltrar = new javax.swing.JButton();
        LABELpesquisarref1 = new javax.swing.JLabel();
        TXTpesquisarmod = new javax.swing.JTextField();
        LABELpesquisarref2 = new javax.swing.JLabel();
        TXTpesquisartam = new javax.swing.JTextField();
        TXTpesquisarcor = new javax.swing.JTextField();
        LABELpesquisarref3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GERENCIADOR DE PRODUTOS - SilhuettaSystem");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(236, 230, 230));

        Pregistradordeprodutos.setBackground(new java.awt.Color(174, 144, 84));

        Lregistradordeprodutos.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Lregistradordeprodutos.setForeground(new java.awt.Color(255, 255, 255));
        Lregistradordeprodutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/PRODUTOSBRANCO.png"))); // NOI18N
        Lregistradordeprodutos.setText("GERENCIADOR   DE   PRODUTOS");
        Lregistradordeprodutos.setAlignmentX(0.1F);
        Lregistradordeprodutos.setIconTextGap(5);
        Lregistradordeprodutos.setMaximumSize(new java.awt.Dimension(200, 30));
        Lregistradordeprodutos.setPreferredSize(new java.awt.Dimension(200, 30));

        Bconsultaestoque.setBackground(new java.awt.Color(174, 144, 84));
        Bconsultaestoque.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Bconsultaestoque.setForeground(new java.awt.Color(255, 255, 255));
        Bconsultaestoque.setText("Consultar Estoque >");
        Bconsultaestoque.setBorderPainted(false);
        Bconsultaestoque.setContentAreaFilled(false);
        Bconsultaestoque.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Bconsultaestoque.setHideActionText(true);
        Bconsultaestoque.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Bconsultaestoque.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Bconsultaestoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BconsultaestoqueMouseClicked(evt);
            }
        });
        Bconsultaestoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BconsultaestoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PregistradordeprodutosLayout = new javax.swing.GroupLayout(Pregistradordeprodutos);
        Pregistradordeprodutos.setLayout(PregistradordeprodutosLayout);
        PregistradordeprodutosLayout.setHorizontalGroup(
            PregistradordeprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PregistradordeprodutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lregistradordeprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Bconsultaestoque)
                .addContainerGap())
        );
        PregistradordeprodutosLayout.setVerticalGroup(
            PregistradordeprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PregistradordeprodutosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PregistradordeprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lregistradordeprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bconsultaestoque)))
        );

        Bexcluir.setBackground(new java.awt.Color(227, 227, 227));
        Bexcluir.setForeground(new java.awt.Color(0, 0, 0));
        Bexcluir.setText("Excluir");
        Bexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BexcluirActionPerformed(evt);
            }
        });

        Bnovo.setBackground(new java.awt.Color(227, 227, 227));
        Bnovo.setForeground(new java.awt.Color(0, 0, 0));
        Bnovo.setText("Limpar");
        Bnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnovoActionPerformed(evt);
            }
        });

        Balterar.setBackground(new java.awt.Color(227, 227, 227));
        Balterar.setForeground(new java.awt.Color(0, 0, 0));
        Balterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ALTERAR.png"))); // NOI18N
        Balterar.setText("Editar");
        Balterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalterarActionPerformed(evt);
            }
        });

        Bsalvar.setBackground(new java.awt.Color(227, 227, 227));
        Bsalvar.setForeground(new java.awt.Color(0, 0, 0));
        Bsalvar.setText("Salvar");
        Bsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsalvarActionPerformed(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        PAINELcadastrarclientes.setBackground(new java.awt.Color(255, 255, 255));

        LABELcodigo.setForeground(new java.awt.Color(0, 0, 0));
        LABELcodigo.setText("CÓDIGO:");

        TXTcodigo.setEditable(false);
        TXTcodigo.setBackground(new java.awt.Color(197, 205, 222));
        TXTcodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTcodigo.setForeground(new java.awt.Color(0, 0, 0));
        TXTcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTcodigoActionPerformed(evt);
            }
        });

        LABELmodelo.setForeground(new java.awt.Color(0, 0, 0));
        LABELmodelo.setText("Modelo:");

        TXTmodelo.setBackground(new java.awt.Color(242, 242, 242));
        TXTmodelo.setForeground(new java.awt.Color(0, 0, 0));

        LABELreferencia.setForeground(new java.awt.Color(0, 0, 0));
        LABELreferencia.setText("Referência:");

        TXTreferencia.setBackground(new java.awt.Color(242, 242, 242));
        TXTreferencia.setForeground(new java.awt.Color(0, 0, 0));

        LABELfornecedor.setForeground(new java.awt.Color(0, 0, 0));
        LABELfornecedor.setText("Fornecedor:");

        LABELtipo.setForeground(new java.awt.Color(0, 0, 0));
        LABELtipo.setText("Tipo:");

        TXTtipo.setBackground(new java.awt.Color(242, 242, 242));
        TXTtipo.setForeground(new java.awt.Color(0, 0, 0));

        TXTcor.setBackground(new java.awt.Color(242, 242, 242));
        TXTcor.setForeground(new java.awt.Color(0, 0, 0));
        TXTcor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTcorActionPerformed(evt);
            }
        });
        TXTcor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTcorKeyPressed(evt);
            }
        });

        LABELcor.setForeground(new java.awt.Color(0, 0, 0));
        LABELcor.setText("Cor:");

        LABELtamanho.setForeground(new java.awt.Color(0, 0, 0));
        LABELtamanho.setText("Tamanho:");

        TXTtamanho.setBackground(new java.awt.Color(242, 242, 242));
        TXTtamanho.setForeground(new java.awt.Color(0, 0, 0));

        LABELcusto.setForeground(new java.awt.Color(0, 0, 0));
        LABELcusto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LABELcusto.setText("Custo:");

        TXTcusto.setBackground(new java.awt.Color(242, 242, 242));
        TXTcusto.setForeground(new java.awt.Color(0, 0, 0));

        LABELquantidade.setForeground(new java.awt.Color(0, 0, 0));
        LABELquantidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LABELquantidade.setText("Quantidade:");

        TXTquantidade.setBackground(new java.awt.Color(242, 242, 242));
        TXTquantidade.setForeground(new java.awt.Color(0, 0, 0));

        TXTfornecedor.setBackground(new java.awt.Color(242, 242, 242));
        TXTfornecedor.setForeground(new java.awt.Color(0, 0, 0));

        LABELcodigo1.setForeground(new java.awt.Color(0, 0, 0));
        LABELcodigo1.setText("Buscar (ID):");

        TXTbuscaid.setBackground(new java.awt.Color(242, 242, 242));
        TXTbuscaid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTbuscaid.setForeground(new java.awt.Color(0, 0, 0));
        TXTbuscaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTbuscaidActionPerformed(evt);
            }
        });

        Bbuscar.setBackground(new java.awt.Color(195, 195, 195));
        Bbuscar.setForeground(new java.awt.Color(0, 0, 0));
        Bbuscar.setText("Buscar");
        Bbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbuscarActionPerformed(evt);
            }
        });

        LABELcodigo2.setForeground(new java.awt.Color(0, 0, 0));
        LABELcodigo2.setText("ID:");

        TXTid.setEditable(false);
        TXTid.setBackground(new java.awt.Color(197, 205, 222));
        TXTid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTid.setForeground(new java.awt.Color(0, 0, 0));
        TXTid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PAINELcadastrarclientesLayout = new javax.swing.GroupLayout(PAINELcadastrarclientes);
        PAINELcadastrarclientes.setLayout(PAINELcadastrarclientesLayout);
        PAINELcadastrarclientesLayout.setHorizontalGroup(
            PAINELcadastrarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAINELcadastrarclientesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PAINELcadastrarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PAINELcadastrarclientesLayout.createSequentialGroup()
                        .addComponent(LABELcodigo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTbuscaid, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addGroup(PAINELcadastrarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LABELcodigo)
                            .addComponent(LABELcodigo2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PAINELcadastrarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTid, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PAINELcadastrarclientesLayout.createSequentialGroup()
                        .addGroup(PAINELcadastrarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LABELquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PAINELcadastrarclientesLayout.createSequentialGroup()
                                .addGroup(PAINELcadastrarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LABELtipo)
                                    .addComponent(LABELcor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PAINELcadastrarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TXTcor)
                                    .addComponent(TXTtipo, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)))
                            .addGroup(PAINELcadastrarclientesLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(PAINELcadastrarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PAINELcadastrarclientesLayout.createSequentialGroup()
                                        .addComponent(LABELfornecedor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TXTfornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PAINELcadastrarclientesLayout.createSequentialGroup()
                                        .addComponent(LABELreferencia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TXTreferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(PAINELcadastrarclientesLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(TXTquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(PAINELcadastrarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PAINELcadastrarclientesLayout.createSequentialGroup()
                                .addGroup(PAINELcadastrarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTcusto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LABELcusto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PAINELcadastrarclientesLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(PAINELcadastrarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LABELmodelo)
                                    .addComponent(LABELtamanho))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PAINELcadastrarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PAINELcadastrarclientesLayout.createSequentialGroup()
                                        .addComponent(TXTtamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(TXTmodelo))))))
                .addContainerGap())
        );
        PAINELcadastrarclientesLayout.setVerticalGroup(
            PAINELcadastrarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAINELcadastrarclientesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PAINELcadastrarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELcodigo1)
                    .addComponent(TXTbuscaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bbuscar)
                    .addComponent(LABELcodigo2)
                    .addComponent(TXTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PAINELcadastrarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABELcodigo))
                .addGap(43, 43, 43)
                .addGroup(PAINELcadastrarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PAINELcadastrarclientesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addGroup(PAINELcadastrarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTcor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LABELcor))
                        .addGap(31, 31, 31)
                        .addGroup(PAINELcadastrarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LABELtipo)
                            .addComponent(TXTtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(PAINELcadastrarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PAINELcadastrarclientesLayout.createSequentialGroup()
                                .addComponent(LABELquantidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PAINELcadastrarclientesLayout.createSequentialGroup()
                                .addComponent(LABELcusto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTcusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))
                    .addGroup(PAINELcadastrarclientesLayout.createSequentialGroup()
                        .addGroup(PAINELcadastrarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LABELreferencia)
                            .addComponent(TXTreferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LABELmodelo))
                        .addGap(28, 28, 28)
                        .addGroup(PAINELcadastrarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LABELfornecedor)
                            .addComponent(TXTfornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTtamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LABELtamanho))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Cadastrar Produto", PAINELcadastrarclientes);

        PAINELprocurarprodutos.setBackground(new java.awt.Color(255, 255, 255));

        TABprodutos.setBackground(new java.awt.Color(255, 255, 255));
        TABprodutos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TABprodutos.setForeground(new java.awt.Color(0, 0, 0));
        TABprodutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Código", "Referência", "Custo", "Quantidade", "Fornecedor", "Modelo", "Tipo", "Tamanho", "Cor"
            }
        ));
        TABprodutos.setFocusable(false);
        TABprodutos.setGridColor(new java.awt.Color(204, 204, 204));
        TABprodutos.setSelectionBackground(new java.awt.Color(0, 0, 0));
        TABprodutos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        TABprodutos.setShowGrid(true);
        TABprodutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABprodutosMouseClicked(evt);
            }
        });
        PAINELprodutos.setViewportView(TABprodutos);

        LABELpesquisarref.setForeground(new java.awt.Color(0, 0, 0));
        LABELpesquisarref.setText("Referência:");

        TXTpesquisarref.setBackground(new java.awt.Color(242, 242, 242));
        TXTpesquisarref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTpesquisarrefActionPerformed(evt);
            }
        });
        TXTpesquisarref.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTpesquisarrefKeyPressed(evt);
            }
        });

        Bfiltrar.setBackground(new java.awt.Color(195, 195, 195));
        Bfiltrar.setForeground(new java.awt.Color(0, 0, 0));
        Bfiltrar.setText("Atualizar");
        Bfiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BfiltrarActionPerformed(evt);
            }
        });

        LABELpesquisarref1.setForeground(new java.awt.Color(0, 0, 0));
        LABELpesquisarref1.setText("Modelo:");

        TXTpesquisarmod.setBackground(new java.awt.Color(242, 242, 242));
        TXTpesquisarmod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTpesquisarmodKeyPressed(evt);
            }
        });

        LABELpesquisarref2.setForeground(new java.awt.Color(0, 0, 0));
        LABELpesquisarref2.setText("Tamanho:");

        TXTpesquisartam.setBackground(new java.awt.Color(242, 242, 242));
        TXTpesquisartam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTpesquisartamKeyPressed(evt);
            }
        });

        TXTpesquisarcor.setBackground(new java.awt.Color(242, 242, 242));
        TXTpesquisarcor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTpesquisarcorKeyPressed(evt);
            }
        });

        LABELpesquisarref3.setForeground(new java.awt.Color(0, 0, 0));
        LABELpesquisarref3.setText("Cor:");

        javax.swing.GroupLayout PAINELprocurarprodutosLayout = new javax.swing.GroupLayout(PAINELprocurarprodutos);
        PAINELprocurarprodutos.setLayout(PAINELprocurarprodutosLayout);
        PAINELprocurarprodutosLayout.setHorizontalGroup(
            PAINELprocurarprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAINELprocurarprodutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PAINELprocurarprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PAINELprodutos, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                    .addGroup(PAINELprocurarprodutosLayout.createSequentialGroup()
                        .addGroup(PAINELprocurarprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PAINELprocurarprodutosLayout.createSequentialGroup()
                                .addGroup(PAINELprocurarprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LABELpesquisarref)
                                    .addComponent(LABELpesquisarref1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PAINELprocurarprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTpesquisarref, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PAINELprocurarprodutosLayout.createSequentialGroup()
                                        .addGroup(PAINELprocurarprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PAINELprocurarprodutosLayout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(TXTpesquisartam, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(TXTpesquisarmod, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(119, 119, 119)
                                        .addComponent(LABELpesquisarref3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TXTpesquisarcor, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Bfiltrar))))
                            .addGroup(PAINELprocurarprodutosLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(LABELpesquisarref2)))
                        .addGap(0, 114, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PAINELprocurarprodutosLayout.setVerticalGroup(
            PAINELprocurarprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAINELprocurarprodutosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PAINELprocurarprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELpesquisarref)
                    .addComponent(TXTpesquisarref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(PAINELprocurarprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELpesquisarref1)
                    .addComponent(TXTpesquisarmod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABELpesquisarref3)
                    .addComponent(TXTpesquisarcor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bfiltrar))
                .addGap(19, 19, 19)
                .addGroup(PAINELprocurarprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELpesquisarref2)
                    .addComponent(TXTpesquisartam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 19, Short.MAX_VALUE)
                .addComponent(PAINELprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Procurar (Filtrar)", PAINELprocurarprodutos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pregistradordeprodutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Bexcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bnovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Balterar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bsalvar)
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Pregistradordeprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bexcluir)
                    .addComponent(Bnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Balterar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bsalvar))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsalvarActionPerformed
        try {
            Produtos obj = new Produtos();
            char ultimoCaractere = TXTtipo.getText().charAt(TXTtipo.getText().length() - 1);
            String codigo = TXTfornecedor.getText().toUpperCase() + TXTreferencia.getText() + ultimoCaractere + TXTtamanho.getText().toUpperCase() + TXTcor.getText().toUpperCase().substring(0,3);
            
            obj.setCodigo (codigo); 
            obj.setReferencia (TXTreferencia.getText());
            obj.setCusto(Double.parseDouble  (TXTcusto.getText()));
            obj.setQuantidade    (Integer.parseInt    (TXTquantidade.getText()));            
            obj.setFornecedor  (TXTfornecedor.getText());                       
            obj.setModelo(TXTmodelo.getText());
            obj.setTipo(TXTtipo.getText());
            obj.setTamanho(TXTtamanho.getText());
            obj.setCor(TXTcor.getText());
            
            
            ProdutosDAO dao = new ProdutosDAO();
            dao.cadastrarProduto(obj);
            
            new Utilitarios().limpaTela(PAINELcadastrarclientes);
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_BsalvarActionPerformed

    private void BnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnovoActionPerformed
        new Utilitarios().limpaTela(PAINELcadastrarclientes);        
    }//GEN-LAST:event_BnovoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void TABprodutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABprodutosMouseClicked
        
        
        jTabbedPane1.setSelectedIndex(0);
        
        TXTid.setText(TABprodutos.getValueAt(TABprodutos.getSelectedRow(), 0).toString());
        TXTcodigo.setText (TABprodutos.getValueAt(TABprodutos.getSelectedRow(), 1).toString());
        TXTreferencia.setText(TABprodutos.getValueAt(TABprodutos.getSelectedRow(), 2).toString());
        TXTcusto.setText(TABprodutos.getValueAt(TABprodutos.getSelectedRow(), 3).toString());
        TXTquantidade.setText(TABprodutos.getValueAt(TABprodutos.getSelectedRow(), 4).toString());
        TXTfornecedor.setText(TABprodutos.getValueAt(TABprodutos.getSelectedRow(), 5).toString());
        TXTmodelo.setText (TABprodutos.getValueAt(TABprodutos.getSelectedRow(), 6).toString());
        TXTtipo.setText (TABprodutos.getValueAt(TABprodutos.getSelectedRow(), 7).toString());
        TXTtamanho.setText (TABprodutos.getValueAt(TABprodutos.getSelectedRow(), 8).toString());
        TXTcor.setText(TABprodutos.getValueAt(TABprodutos.getSelectedRow(), 9).toString());

    }//GEN-LAST:event_TABprodutosMouseClicked

    private void BalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalterarActionPerformed
        try {
            
            Produtos obj = new Produtos();
            
            obj.setCodigo(TXTcodigo.getText());
            obj.setReferencia(TXTreferencia.getText());
            obj.setCusto(Double.parseDouble(TXTcusto.getText()));
            obj.setQuantidade(Integer.parseInt(TXTquantidade.getText()));
            obj.setFornecedor(TXTfornecedor.getText());
            obj.setModelo(TXTmodelo.getText());
            obj.setTipo(TXTtipo.getText());
            obj.setTamanho(TXTtamanho.getText());
            obj.setCor (TXTcor.getText());     
            
            obj.setId(Integer.parseInt(TXTid.getText()));
            
            ProdutosDAO dao = new ProdutosDAO();
            dao.alterarProduto(obj);
            
            new Utilitarios().limpaTela(PAINELcadastrarclientes);
            
            } catch (Exception e) {
        }
    }//GEN-LAST:event_BalterarActionPerformed

    private void BexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BexcluirActionPerformed
        try {
            
            Produtos obj = new Produtos();
            
            obj.setId(Integer.parseInt(TXTid.getText()));
            
            ProdutosDAO dao = new ProdutosDAO();
            dao.excluirProduto(obj);
            
            new Utilitarios().limpaTela(PAINELcadastrarclientes);
            
            } catch (Exception e) {
        }
    }//GEN-LAST:event_BexcluirActionPerformed

    private void BfiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BfiltrarActionPerformed

        String referencia = "%" + TXTpesquisarref.getText() + "%";
        String modelo = "%" + TXTpesquisarmod.getText() + "%";
        String tamanho = "%" + TXTpesquisartam.getText() + "%";
        String cor = "%" + TXTpesquisarcor.getText() + "%";
        
        ProdutosDAO dao = new ProdutosDAO();
        List<Produtos> lista = dao.buscaProdutosPorFiltro(referencia,modelo,tamanho,cor);
        DefaultTableModel dados = (DefaultTableModel) TABprodutos.getModel();
        dados.setNumRows(0);
        
        for (Produtos p: lista){
            dados.addRow(new Object[]{
                p.getId(),
                p.getCodigo(),
                p.getReferencia(),
                p.getCusto(),
                p.getQuantidade(),
                p.getFornecedor(),
                p.getModelo(),
                p.getTipo(),
                p.getTamanho(),
                p.getCor(), 
                
        });
        }
        
    }//GEN-LAST:event_BfiltrarActionPerformed

    private void TXTpesquisarrefKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTpesquisarrefKeyPressed
                
    }//GEN-LAST:event_TXTpesquisarrefKeyPressed

    private void TXTcorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTcorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTcorActionPerformed

    private void TXTcorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTcorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTcorKeyPressed

    private void BconsultaestoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BconsultaestoqueMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BconsultaestoqueMouseClicked

    private void BconsultaestoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BconsultaestoqueActionPerformed
        ViewEstoque tela = new ViewEstoque();
        tela.setVisible(true);
    }//GEN-LAST:event_BconsultaestoqueActionPerformed

    private void TXTpesquisarmodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTpesquisarmodKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTpesquisarmodKeyPressed

    private void TXTpesquisartamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTpesquisartamKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTpesquisartamKeyPressed

    private void TXTpesquisarcorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTpesquisarcorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTpesquisarcorKeyPressed

    private void TXTcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTcodigoActionPerformed

    private void TXTbuscaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTbuscaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTbuscaidActionPerformed

    private void BbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbuscarActionPerformed

        Produtos obj = new Produtos();
        ProdutosDAO dao = new ProdutosDAO();

        obj = dao.consultaPorId(Integer.parseInt(TXTbuscaid.getText()));

        if(obj.getId()>= 1){

            TXTid.setText(String.valueOf(obj.getId()));
            TXTcodigo.setText(obj.getCodigo());
            TXTreferencia.setText(obj.getReferencia());
            TXTmodelo.setText(obj.getModelo());
            TXTcor.setText(obj.getCor());
            TXTfornecedor.setText(obj.getFornecedor());
            TXTtamanho.setText(obj.getTamanho());
            TXTtipo.setText (obj.getTipo());
            TXTquantidade.setText(String.valueOf(obj.getQuantidade()));
            TXTcusto.setText(String.valueOf(obj.getCusto()));

        } else {
            JOptionPane.showMessageDialog(null, "Erro: Cliente Não Encontrado.");
        }
    }//GEN-LAST:event_BbuscarActionPerformed

    private void TXTidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTidActionPerformed

    private void TXTpesquisarrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTpesquisarrefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTpesquisarrefActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Balterar;
    private javax.swing.JButton Bbuscar;
    private javax.swing.JButton Bconsultaestoque;
    private javax.swing.JButton Bexcluir;
    private javax.swing.JButton Bfiltrar;
    private javax.swing.JButton Bnovo;
    private javax.swing.JButton Bsalvar;
    private javax.swing.JLabel LABELcodigo;
    private javax.swing.JLabel LABELcodigo1;
    private javax.swing.JLabel LABELcodigo2;
    private javax.swing.JLabel LABELcor;
    private javax.swing.JLabel LABELcusto;
    private javax.swing.JLabel LABELfornecedor;
    private javax.swing.JLabel LABELmodelo;
    private javax.swing.JLabel LABELpesquisarref;
    private javax.swing.JLabel LABELpesquisarref1;
    private javax.swing.JLabel LABELpesquisarref2;
    private javax.swing.JLabel LABELpesquisarref3;
    private javax.swing.JLabel LABELquantidade;
    private javax.swing.JLabel LABELreferencia;
    private javax.swing.JLabel LABELtamanho;
    private javax.swing.JLabel LABELtipo;
    private javax.swing.JLabel Lregistradordeprodutos;
    private javax.swing.JPanel PAINELcadastrarclientes;
    private javax.swing.JPanel PAINELprocurarprodutos;
    private javax.swing.JScrollPane PAINELprodutos;
    private javax.swing.JPanel Pregistradordeprodutos;
    private javax.swing.JTable TABprodutos;
    private javax.swing.JTextField TXTbuscaid;
    private javax.swing.JTextField TXTcodigo;
    private javax.swing.JTextField TXTcor;
    private javax.swing.JTextField TXTcusto;
    private javax.swing.JTextField TXTfornecedor;
    private javax.swing.JTextField TXTid;
    private javax.swing.JTextField TXTmodelo;
    private javax.swing.JTextField TXTpesquisarcor;
    private javax.swing.JTextField TXTpesquisarmod;
    private javax.swing.JTextField TXTpesquisarref;
    private javax.swing.JTextField TXTpesquisartam;
    private javax.swing.JTextField TXTquantidade;
    private javax.swing.JTextField TXTreferencia;
    private javax.swing.JTextField TXTtamanho;
    private javax.swing.JTextField TXTtipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
