/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ItensVendaDAO;
import dao.ProdutosDAO;
import dao.VendasDAO;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ItemVenda;
import model.Produtos;
import model.Vendas;

/**
 *
 * @author caio
 */
public class ViewPagamentos extends javax.swing.JFrame {

    /**
     * Creates new form ViewPagamentos
     */
    
    DefaultTableModel carrinho;
    
    public ViewPagamentos() {
        initComponents();
        
        TXTpix.setText("0");
        TXTdinheiro.setText("0");
        TXTcheque.setText("0");
        TXTtroco.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Pregistradordeprodutos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LABELdinheiro = new javax.swing.JLabel();
        TXTdinheiro = new javax.swing.JTextField();
        LABELcartao = new javax.swing.JLabel();
        TXTpix = new javax.swing.JTextField();
        LABELcheque = new javax.swing.JLabel();
        TXTcheque = new javax.swing.JTextField();
        LABELtotal = new javax.swing.JLabel();
        TXTtotal = new javax.swing.JTextField();
        LABELtroco = new javax.swing.JLabel();
        TXTtroco = new javax.swing.JTextField();
        Bfinalizar = new javax.swing.JButton();
        LABELobs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXTobs = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PAGAMENTO - SilhuettaSystem");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(236, 230, 230));

        Pregistradordeprodutos.setBackground(new java.awt.Color(84, 125, 174));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logo-Sullhueta-BRANCO.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/PAGAMENTO.png"))); // NOI18N
        jLabel2.setText("FINALIZAR PAGAMENTO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PregistradordeprodutosLayout = new javax.swing.GroupLayout(Pregistradordeprodutos);
        Pregistradordeprodutos.setLayout(PregistradordeprodutosLayout);
        PregistradordeprodutosLayout.setHorizontalGroup(
            PregistradordeprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PregistradordeprodutosLayout.setVerticalGroup(
            PregistradordeprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PregistradordeprodutosLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LABELdinheiro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LABELdinheiro.setForeground(new java.awt.Color(0, 0, 0));
        LABELdinheiro.setText("Dinheiro (R$):");

        TXTdinheiro.setBackground(new java.awt.Color(255, 255, 255));
        TXTdinheiro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTdinheiro.setForeground(new java.awt.Color(0, 0, 0));

        LABELcartao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LABELcartao.setForeground(new java.awt.Color(0, 0, 0));
        LABELcartao.setText("PIX:");

        TXTpix.setBackground(new java.awt.Color(255, 255, 255));
        TXTpix.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTpix.setForeground(new java.awt.Color(0, 0, 0));

        LABELcheque.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LABELcheque.setForeground(new java.awt.Color(0, 0, 0));
        LABELcheque.setText("Cheque:");

        TXTcheque.setBackground(new java.awt.Color(255, 255, 255));
        TXTcheque.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTcheque.setForeground(new java.awt.Color(0, 0, 0));

        LABELtotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LABELtotal.setForeground(new java.awt.Color(0, 0, 0));
        LABELtotal.setText("Total:");

        TXTtotal.setEditable(false);
        TXTtotal.setBackground(new java.awt.Color(197, 205, 222));
        TXTtotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTtotal.setForeground(new java.awt.Color(102, 102, 102));

        LABELtroco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LABELtroco.setForeground(new java.awt.Color(0, 0, 0));
        LABELtroco.setText("Troco:");

        TXTtroco.setEditable(false);
        TXTtroco.setBackground(new java.awt.Color(197, 205, 222));
        TXTtroco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTtroco.setForeground(new java.awt.Color(51, 51, 51));

        Bfinalizar.setBackground(new java.awt.Color(195, 195, 195));
        Bfinalizar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Bfinalizar.setForeground(new java.awt.Color(0, 0, 0));
        Bfinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/FINALIZA.png"))); // NOI18N
        Bfinalizar.setText("Finalizar Compra");
        Bfinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BfinalizarActionPerformed(evt);
            }
        });

        LABELobs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LABELobs.setForeground(new java.awt.Color(0, 0, 0));
        LABELobs.setText("Obs.:");

        TXTobs.setBackground(new java.awt.Color(255, 255, 255));
        TXTobs.setColumns(20);
        TXTobs.setForeground(new java.awt.Color(0, 0, 0));
        TXTobs.setRows(5);
        jScrollPane1.setViewportView(TXTobs);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pregistradordeprodutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LABELdinheiro)
                            .addComponent(LABELcartao, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LABELcheque, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TXTpix, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTdinheiro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTcheque, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LABELtotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LABELtroco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTtroco, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LABELobs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Bfinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Pregistradordeprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LABELdinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTdinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LABELcartao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTpix, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LABELcheque, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTcheque, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LABELtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LABELtroco, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTtroco, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(LABELobs, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(156, 156, 156))
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(Bfinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BfinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BfinalizarActionPerformed
        double pcartao,pcheque,pdinheiro,totalpago,totalvenda,troco;
        
        pcartao = Double.parseDouble(TXTpix.getText());
        pdinheiro = Double.parseDouble(TXTdinheiro.getText());
        pcheque = Double.parseDouble(TXTcheque.getText());
        totalvenda = Double.parseDouble(TXTtotal.getText());
        
        totalpago = pcartao + pcheque + pdinheiro;
        
        troco = totalvenda - totalpago;
        TXTtroco.setText(String.valueOf(troco));
        
        Vendas objv = new Vendas();
        
        Date agora = new Date();
        SimpleDateFormat dataEUA = new SimpleDateFormat("yyyy-MM-dd");
        String datamysql = dataEUA.format(agora);
        objv.setData_venda(datamysql);
        
        objv.setTotal_venda(totalvenda);
        
        objv.setObs(TXTobs.getText());
        
        VendasDAO daov = new VendasDAO();
        daov.cadastrarVenda(objv);
        
        
        objv.setId(daov.retornaIdUltimaVenda());
        
        
        
        for (int i = 0; i < carrinho.getRowCount(); i++){
            
            int quantidade,quantidadecomprada,quantidadeatualizada;
            
            Produtos objp = new Produtos();
            ProdutosDAO daoprodutos = new ProdutosDAO(); 
            
            ItemVenda item = new ItemVenda();                        
            item.setVenda (objv);
            
            objp.setId(Integer.parseInt(carrinho.getValueAt(i, 0).toString()));
            item.setProduto(objp);
            item.setCor(objp);
            item.setQnt(Integer.parseInt(carrinho.getValueAt(i, 3).toString()));
            item.setSubtotal (Double.parseDouble(carrinho.getValueAt(i, 5).toString()));
            
            quantidade = daoprodutos.retornaEstoqueAtual(objp.getReferencia());
            quantidadecomprada = (Integer.parseInt(carrinho.getValueAt(i, 3).toString()));
            quantidadeatualizada = quantidade - quantidadecomprada;
            
            daoprodutos.baixaEstoque (objp.getId(), quantidadeatualizada);
            
            ItensVendaDAO daoitem = new ItensVendaDAO();
            daoitem.cadastrarItem(item);
            
        }
        
        JOptionPane.showMessageDialog  (null,"Venda Registrada com SUCESSO!");
        ViewVendas telavendas = new ViewVendas();
        this.dispose(); 
        telavendas.setVisible(true);
        
    }//GEN-LAST:event_BfinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPagamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bfinalizar;
    private javax.swing.JLabel LABELcartao;
    private javax.swing.JLabel LABELcheque;
    private javax.swing.JLabel LABELdinheiro;
    private javax.swing.JLabel LABELobs;
    private javax.swing.JLabel LABELtotal;
    private javax.swing.JLabel LABELtroco;
    private javax.swing.JPanel Pregistradordeprodutos;
    private javax.swing.JTextField TXTcheque;
    private javax.swing.JTextField TXTdinheiro;
    private javax.swing.JTextArea TXTobs;
    private javax.swing.JTextField TXTpix;
    public javax.swing.JTextField TXTtotal;
    private javax.swing.JTextField TXTtroco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
