/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.FuncionariosDAO;
import java.awt.event.KeyEvent;
import model.Funcionarios;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Utilitarios;

/**
 *
 * @author caio
 */
public class ViewFuncionarios extends javax.swing.JFrame {

    /**
     * Creates new form ViewClientes
     */
    
    public void listar(){
        
        FuncionariosDAO dao = new FuncionariosDAO();
        List<Funcionarios> lista = dao.listarFuncionarios();
        DefaultTableModel dados = (DefaultTableModel) TABfuncionarios.getModel();
        dados.setNumRows(0);
        
        for (Funcionarios f: lista){
            dados.addRow(new Object[]{
            
                f.getId(),
                f.getNome(),
                f.getRg(),
                f.getCpf(),
                f.getEmail(),
                f.getSenha(),
                f.getCargo(),
                f.getNivel_acesso(),
                f.getTelefone(),
                f.getCelular(),
                f.getCep(),
                f.getEndereco(),
                f.getNumero(),
                f.getComplemento(),
                f.getBairro(),
                f.getCidade(),
                f.getUf(),
        });
        }
    }
    
    public ViewFuncionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Pregistradordeprodutos = new javax.swing.JPanel();
        Lregistradordeprodutos = new javax.swing.JLabel();
        Bexcluir = new javax.swing.JButton();
        Bnovo = new javax.swing.JButton();
        Balterar = new javax.swing.JButton();
        Bsalvar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PAINELcadastrarfuncionarios = new javax.swing.JPanel();
        LABELid = new javax.swing.JLabel();
        TXTid = new javax.swing.JTextField();
        LABELnome = new javax.swing.JLabel();
        TXTnome = new javax.swing.JTextField();
        LABELemail = new javax.swing.JLabel();
        TXTlogin = new javax.swing.JTextField();
        LABELcelular = new javax.swing.JLabel();
        LABELtelefone = new javax.swing.JLabel();
        LABELcep = new javax.swing.JLabel();
        TXTcep = new javax.swing.JTextField();
        LABELendereco = new javax.swing.JLabel();
        TXTendereco = new javax.swing.JTextField();
        LABELnumero = new javax.swing.JLabel();
        TXTnumero = new javax.swing.JTextField();
        LABELcidade = new javax.swing.JLabel();
        TXTcidade = new javax.swing.JTextField();
        LABELbairro = new javax.swing.JLabel();
        TXTbairro = new javax.swing.JTextField();
        LABELcomplemento = new javax.swing.JLabel();
        TXTcomplemento = new javax.swing.JTextField();
        LABELuf = new javax.swing.JLabel();
        CBOXuf = new javax.swing.JComboBox<>();
        LABELcpf = new javax.swing.JLabel();
        LABELrg = new javax.swing.JLabel();
        LABELsenha = new javax.swing.JLabel();
        TXTsenha = new javax.swing.JPasswordField();
        LABELcargo = new javax.swing.JLabel();
        TXTcargo = new javax.swing.JTextField();
        LABELniveldeacesso = new javax.swing.JLabel();
        CBOXnivel_acesso = new javax.swing.JComboBox<>();
        LABELenterparaauto = new javax.swing.JLabel();
        Bbuscar = new javax.swing.JButton();
        TXTcelular = new javax.swing.JFormattedTextField();
        TXTtelefone = new javax.swing.JFormattedTextField();
        TXTcpf = new javax.swing.JFormattedTextField();
        TXTrg = new javax.swing.JFormattedTextField();
        PAINELprocurarfuncionarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABfuncionarios = new javax.swing.JTable();
        LABELpesquisarnome = new javax.swing.JLabel();
        TXTpesquisarnome = new javax.swing.JTextField();
        Bpesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GERENCIADOR DE - SilhuettaSystem");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(236, 230, 230));

        Pregistradordeprodutos.setBackground(new java.awt.Color(84, 125, 174));

        Lregistradordeprodutos.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Lregistradordeprodutos.setForeground(new java.awt.Color(255, 255, 255));
        Lregistradordeprodutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/FUNCIONARIOS BRANCO.png"))); // NOI18N
        Lregistradordeprodutos.setText("GERENCIADOR   DE   FUNCIONÁRIOS");
        Lregistradordeprodutos.setAlignmentX(0.1F);
        Lregistradordeprodutos.setIconTextGap(5);
        Lregistradordeprodutos.setMaximumSize(new java.awt.Dimension(200, 30));
        Lregistradordeprodutos.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout PregistradordeprodutosLayout = new javax.swing.GroupLayout(Pregistradordeprodutos);
        Pregistradordeprodutos.setLayout(PregistradordeprodutosLayout);
        PregistradordeprodutosLayout.setHorizontalGroup(
            PregistradordeprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Lregistradordeprodutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PregistradordeprodutosLayout.setVerticalGroup(
            PregistradordeprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PregistradordeprodutosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Lregistradordeprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Bexcluir.setBackground(new java.awt.Color(227, 227, 227));
        Bexcluir.setForeground(new java.awt.Color(0, 0, 0));
        Bexcluir.setText("Excluir");
        Bexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BexcluirActionPerformed(evt);
            }
        });

        Bnovo.setBackground(new java.awt.Color(227, 227, 227));
        Bnovo.setForeground(new java.awt.Color(0, 0, 0));
        Bnovo.setText("Limpar");
        Bnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnovoActionPerformed(evt);
            }
        });

        Balterar.setBackground(new java.awt.Color(227, 227, 227));
        Balterar.setForeground(new java.awt.Color(0, 0, 0));
        Balterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ALTERAR.png"))); // NOI18N
        Balterar.setText("Editar");
        Balterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalterarActionPerformed(evt);
            }
        });

        Bsalvar.setBackground(new java.awt.Color(227, 227, 227));
        Bsalvar.setForeground(new java.awt.Color(0, 0, 0));
        Bsalvar.setText("Salvar");
        Bsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsalvarActionPerformed(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        PAINELcadastrarfuncionarios.setBackground(new java.awt.Color(255, 255, 255));

        LABELid.setForeground(new java.awt.Color(0, 0, 0));
        LABELid.setText("ID:");

        TXTid.setEditable(false);
        TXTid.setBackground(new java.awt.Color(197, 205, 222));
        TXTid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTid.setForeground(new java.awt.Color(0, 0, 0));

        LABELnome.setForeground(new java.awt.Color(0, 0, 0));
        LABELnome.setText("Nome:");

        TXTnome.setBackground(new java.awt.Color(242, 242, 242));
        TXTnome.setForeground(new java.awt.Color(0, 0, 0));

        LABELemail.setForeground(new java.awt.Color(0, 0, 0));
        LABELemail.setText("Login:");

        TXTlogin.setBackground(new java.awt.Color(242, 242, 242));
        TXTlogin.setForeground(new java.awt.Color(0, 0, 0));

        LABELcelular.setForeground(new java.awt.Color(0, 0, 0));
        LABELcelular.setText("Celular:");

        LABELtelefone.setForeground(new java.awt.Color(0, 0, 0));
        LABELtelefone.setText("Telefone (fixo):");

        LABELcep.setForeground(new java.awt.Color(0, 0, 0));
        LABELcep.setText("CEP:");

        TXTcep.setBackground(new java.awt.Color(242, 242, 242));
        TXTcep.setForeground(new java.awt.Color(0, 0, 0));
        TXTcep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTcepActionPerformed(evt);
            }
        });
        TXTcep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTcepKeyPressed(evt);
            }
        });

        LABELendereco.setForeground(new java.awt.Color(0, 0, 0));
        LABELendereco.setText("Endereço:");

        TXTendereco.setBackground(new java.awt.Color(242, 242, 242));
        TXTendereco.setForeground(new java.awt.Color(0, 0, 0));

        LABELnumero.setForeground(new java.awt.Color(0, 0, 0));
        LABELnumero.setText("Nº :");

        TXTnumero.setBackground(new java.awt.Color(242, 242, 242));
        TXTnumero.setForeground(new java.awt.Color(0, 0, 0));

        LABELcidade.setForeground(new java.awt.Color(0, 0, 0));
        LABELcidade.setText("Cidade:");

        TXTcidade.setBackground(new java.awt.Color(242, 242, 242));
        TXTcidade.setForeground(new java.awt.Color(0, 0, 0));

        LABELbairro.setForeground(new java.awt.Color(0, 0, 0));
        LABELbairro.setText("Bairro");

        TXTbairro.setBackground(new java.awt.Color(242, 242, 242));
        TXTbairro.setForeground(new java.awt.Color(0, 0, 0));

        LABELcomplemento.setForeground(new java.awt.Color(0, 0, 0));
        LABELcomplemento.setText("Complemento:");

        TXTcomplemento.setBackground(new java.awt.Color(242, 242, 242));
        TXTcomplemento.setForeground(new java.awt.Color(0, 0, 0));

        LABELuf.setForeground(new java.awt.Color(0, 0, 0));
        LABELuf.setText("UF:");

        CBOXuf.setBackground(new java.awt.Color(242, 242, 242));
        CBOXuf.setForeground(new java.awt.Color(0, 0, 0));
        CBOXuf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PE", "PB" }));

        LABELcpf.setForeground(new java.awt.Color(0, 0, 0));
        LABELcpf.setText("CPF:");

        LABELrg.setForeground(new java.awt.Color(0, 0, 0));
        LABELrg.setText("RG:");

        LABELsenha.setForeground(new java.awt.Color(0, 0, 0));
        LABELsenha.setText("Senha:");

        TXTsenha.setBackground(new java.awt.Color(242, 242, 242));
        TXTsenha.setForeground(new java.awt.Color(0, 0, 0));

        LABELcargo.setForeground(new java.awt.Color(0, 0, 0));
        LABELcargo.setText("Cargo:");

        TXTcargo.setBackground(new java.awt.Color(242, 242, 242));
        TXTcargo.setForeground(new java.awt.Color(0, 0, 0));

        LABELniveldeacesso.setForeground(new java.awt.Color(0, 0, 0));
        LABELniveldeacesso.setText("Nivel de Acesso:");

        CBOXnivel_acesso.setBackground(new java.awt.Color(242, 242, 242));
        CBOXnivel_acesso.setForeground(new java.awt.Color(0, 0, 0));
        CBOXnivel_acesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuário", "Administrador" }));

        LABELenterparaauto.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        LABELenterparaauto.setForeground(new java.awt.Color(0, 0, 0));
        LABELenterparaauto.setText("(ENTER para auto)");

        Bbuscar.setBackground(new java.awt.Color(195, 195, 195));
        Bbuscar.setForeground(new java.awt.Color(0, 0, 0));
        Bbuscar.setText("Buscar");
        Bbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbuscarActionPerformed(evt);
            }
        });

        TXTcelular.setBackground(new java.awt.Color(242, 242, 242));
        TXTcelular.setForeground(new java.awt.Color(0, 0, 0));
        try {
            TXTcelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TXTcelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTcelularActionPerformed(evt);
            }
        });

        TXTtelefone.setBackground(new java.awt.Color(242, 242, 242));
        TXTtelefone.setForeground(new java.awt.Color(0, 0, 0));
        try {
            TXTtelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TXTtelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTtelefoneActionPerformed(evt);
            }
        });

        TXTcpf.setBackground(new java.awt.Color(242, 242, 242));
        TXTcpf.setForeground(new java.awt.Color(0, 0, 0));
        try {
            TXTcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TXTcpf.setText("");
        TXTcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTcpfActionPerformed(evt);
            }
        });

        TXTrg.setBackground(new java.awt.Color(242, 242, 242));
        TXTrg.setForeground(new java.awt.Color(0, 0, 0));
        try {
            TXTrg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TXTrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTrgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PAINELcadastrarfuncionariosLayout = new javax.swing.GroupLayout(PAINELcadastrarfuncionarios);
        PAINELcadastrarfuncionarios.setLayout(PAINELcadastrarfuncionariosLayout);
        PAINELcadastrarfuncionariosLayout.setHorizontalGroup(
            PAINELcadastrarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAINELcadastrarfuncionariosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PAINELcadastrarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PAINELcadastrarfuncionariosLayout.createSequentialGroup()
                        .addGroup(PAINELcadastrarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(PAINELcadastrarfuncionariosLayout.createSequentialGroup()
                                .addComponent(LABELsenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTsenha))
                            .addGroup(PAINELcadastrarfuncionariosLayout.createSequentialGroup()
                                .addComponent(LABELcomplemento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(PAINELcadastrarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PAINELcadastrarfuncionariosLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(LABELuf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CBOXuf, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LABELnumero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PAINELcadastrarfuncionariosLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(PAINELcadastrarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PAINELcadastrarfuncionariosLayout.createSequentialGroup()
                                        .addComponent(LABELcargo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TXTcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAINELcadastrarfuncionariosLayout.createSequentialGroup()
                                        .addComponent(LABELniveldeacesso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CBOXnivel_acesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(PAINELcadastrarfuncionariosLayout.createSequentialGroup()
                        .addGroup(PAINELcadastrarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LABELemail)
                            .addComponent(LABELid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PAINELcadastrarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PAINELcadastrarfuncionariosLayout.createSequentialGroup()
                                .addGroup(PAINELcadastrarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(PAINELcadastrarfuncionariosLayout.createSequentialGroup()
                                        .addGap(115, 115, 115)
                                        .addComponent(LABELenterparaauto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LABELendereco))
                                    .addComponent(LABELbairro)
                                    .addGroup(PAINELcadastrarfuncionariosLayout.createSequentialGroup()
                                        .addComponent(TXTlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LABELcelular)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PAINELcadastrarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PAINELcadastrarfuncionariosLayout.createSequentialGroup()
                                        .addComponent(TXTcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LABELtelefone)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TXTtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TXTendereco)
                                    .addComponent(TXTbairro)))
                            .addGroup(PAINELcadastrarfuncionariosLayout.createSequentialGroup()
                                .addComponent(TXTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LABELnome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTnome, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PAINELcadastrarfuncionariosLayout.createSequentialGroup()
                        .addGroup(PAINELcadastrarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PAINELcadastrarfuncionariosLayout.createSequentialGroup()
                                .addComponent(LABELcep)
                                .addGap(18, 18, 18)
                                .addComponent(TXTcep, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PAINELcadastrarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PAINELcadastrarfuncionariosLayout.createSequentialGroup()
                                    .addComponent(LABELcpf)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TXTcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(13, 13, 13)
                                    .addComponent(LABELrg)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TXTrg, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PAINELcadastrarfuncionariosLayout.createSequentialGroup()
                                    .addComponent(LABELcidade)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TXTcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(44, 44, 44))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(51, 51, 51))
        );
        PAINELcadastrarfuncionariosLayout.setVerticalGroup(
            PAINELcadastrarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAINELcadastrarfuncionariosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PAINELcadastrarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELid)
                    .addComponent(TXTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABELnome)
                    .addComponent(TXTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PAINELcadastrarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELcelular)
                    .addComponent(LABELemail)
                    .addComponent(TXTlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABELtelefone)
                    .addComponent(TXTcelular)
                    .addComponent(TXTtelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PAINELcadastrarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELcep)
                    .addComponent(TXTcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABELendereco)
                    .addComponent(TXTendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABELenterparaauto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PAINELcadastrarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELcidade)
                    .addComponent(TXTcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABELbairro)
                    .addComponent(TXTbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PAINELcadastrarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELuf)
                    .addComponent(CBOXuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABELcomplemento)
                    .addComponent(TXTcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABELnumero)
                    .addComponent(TXTnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PAINELcadastrarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELsenha)
                    .addComponent(TXTsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABELcargo)
                    .addComponent(TXTcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PAINELcadastrarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELniveldeacesso)
                    .addComponent(CBOXnivel_acesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(PAINELcadastrarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PAINELcadastrarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LABELrg)
                        .addComponent(TXTrg))
                    .addGroup(PAINELcadastrarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LABELcpf)
                        .addComponent(TXTcpf)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar Funcionário", PAINELcadastrarfuncionarios);

        PAINELprocurarfuncionarios.setBackground(new java.awt.Color(255, 255, 255));

        TABfuncionarios.setBackground(new java.awt.Color(255, 255, 255));
        TABfuncionarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TABfuncionarios.setForeground(new java.awt.Color(0, 0, 0));
        TABfuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "RG", "CPF", "E-mail", "Senha", "Cargo", "Acesso", "Telefone (fixo)", "Celular", "CEP", "Endereço", "Num", "Complemento", "Bairro", "Cidade", "UF"
            }
        ));
        TABfuncionarios.setFocusable(false);
        TABfuncionarios.setGridColor(new java.awt.Color(204, 204, 204));
        TABfuncionarios.setSelectionBackground(new java.awt.Color(0, 0, 0));
        TABfuncionarios.setSelectionForeground(new java.awt.Color(255, 255, 255));
        TABfuncionarios.setShowGrid(true);
        TABfuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABfuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TABfuncionarios);

        LABELpesquisarnome.setForeground(new java.awt.Color(0, 0, 0));
        LABELpesquisarnome.setText("Nome:");

        TXTpesquisarnome.setBackground(new java.awt.Color(242, 242, 242));

        Bpesquisar.setBackground(new java.awt.Color(195, 195, 195));
        Bpesquisar.setForeground(new java.awt.Color(0, 0, 0));
        Bpesquisar.setText("Pesquisar");
        Bpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PAINELprocurarfuncionariosLayout = new javax.swing.GroupLayout(PAINELprocurarfuncionarios);
        PAINELprocurarfuncionarios.setLayout(PAINELprocurarfuncionariosLayout);
        PAINELprocurarfuncionariosLayout.setHorizontalGroup(
            PAINELprocurarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAINELprocurarfuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PAINELprocurarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PAINELprocurarfuncionariosLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(PAINELprocurarfuncionariosLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(LABELpesquisarnome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTpesquisarnome, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bpesquisar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PAINELprocurarfuncionariosLayout.setVerticalGroup(
            PAINELprocurarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAINELprocurarfuncionariosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(PAINELprocurarfuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTpesquisarnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABELpesquisarnome)
                    .addComponent(Bpesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Procurar", PAINELprocurarfuncionarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pregistradordeprodutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Bexcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bnovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Balterar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bsalvar)
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Pregistradordeprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bexcluir)
                    .addComponent(Bnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Balterar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bsalvar))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsalvarActionPerformed
        try {
            
            Funcionarios obj = new Funcionarios();
            obj.setNome(TXTnome.getText());
            obj.setRg(TXTrg.getText());
            obj.setCpf        (TXTcpf.getText());
            obj.setEmail      (TXTlogin.getText());
            obj.setSenha      (TXTsenha.getText());
            obj.setCargo      (TXTcargo.getText());
            obj.setNivel_acesso      (CBOXnivel_acesso.getSelectedItem().toString());
            obj.setTelefone   (TXTcelular.getText());
            obj.setCelular    (TXTcelular.getText());
            obj.setCep        (TXTcep.getText());
            obj.setEndereco   (TXTendereco.getText());
            obj.setNumero     (Integer.parseInt(TXTnumero.getText()));
            obj.setComplemento(TXTcomplemento.getText());
            obj.setBairro     (TXTbairro.getText());
            obj.setCidade     (TXTcidade.getText());
            obj.setUf         (CBOXuf.getSelectedItem().toString());
            
            FuncionariosDAO dao = new FuncionariosDAO();
            dao.cadastrarFuncionarios(obj);
            new Utilitarios().limpaTela(PAINELcadastrarfuncionarios);
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_BsalvarActionPerformed

    private void BnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnovoActionPerformed
new Utilitarios().limpaTela(PAINELcadastrarfuncionarios);        
    }//GEN-LAST:event_BnovoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void TABfuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABfuncionariosMouseClicked
        jTabbedPane1.setSelectedIndex(0);
        
        TXTid.setText(TABfuncionarios.getValueAt(TABfuncionarios.getSelectedRow(), 0).toString());
        TXTnome.setText(TABfuncionarios.getValueAt(TABfuncionarios.getSelectedRow(), 1).toString());
        TXTrg.setText(TABfuncionarios.getValueAt(TABfuncionarios.getSelectedRow(), 2).toString());
        TXTcpf.setText(TABfuncionarios.getValueAt(TABfuncionarios.getSelectedRow(), 3).toString());
        TXTlogin.setText(TABfuncionarios.getValueAt(TABfuncionarios.getSelectedRow(), 4).toString());
        TXTsenha.setText(TABfuncionarios.getValueAt(TABfuncionarios.getSelectedRow(), 5).toString());
        TXTcargo.setText(TABfuncionarios.getValueAt(TABfuncionarios.getSelectedRow(), 6).toString());
        CBOXnivel_acesso.setSelectedItem     (TABfuncionarios.getValueAt(TABfuncionarios.getSelectedRow(), 7).toString());
        TXTcelular.setText(TABfuncionarios.getValueAt(TABfuncionarios.getSelectedRow(), 8).toString());
        TXTcelular.setText(TABfuncionarios.getValueAt  (TABfuncionarios.getSelectedRow(), 9).toString());
        TXTcep.setText   (TABfuncionarios.getValueAt(TABfuncionarios.getSelectedRow(), 10).toString());
        TXTendereco.setText   (TABfuncionarios.getValueAt(TABfuncionarios.getSelectedRow(), 11).toString());
        TXTnumero.setText(TABfuncionarios.getValueAt(TABfuncionarios.getSelectedRow(), 12).toString());
        TXTcomplemento.setText(TABfuncionarios.getValueAt(TABfuncionarios.getSelectedRow(), 13).toString());
        TXTbairro.setText(TABfuncionarios.getValueAt(TABfuncionarios.getSelectedRow(), 14).toString());
        TXTcidade.setText(TABfuncionarios.getValueAt(TABfuncionarios.getSelectedRow(), 15).toString());
        CBOXuf.setSelectedItem(TABfuncionarios.getValueAt(TABfuncionarios.getSelectedRow(), 16).toString());

    }//GEN-LAST:event_TABfuncionariosMouseClicked

    private void BalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalterarActionPerformed
        try {
            
            Funcionarios obj = new Funcionarios();
            obj.setNome(TXTnome.getText());
            obj.setRg(TXTrg.getText());
            obj.setCpf        (TXTcpf.getText());
            obj.setEmail      (TXTlogin.getText());
            obj.setSenha      (TXTsenha.getText());
            obj.setCargo     (TXTcargo.getText());
            obj.setNivel_acesso      (CBOXnivel_acesso.getSelectedItem().toString());
            obj.setTelefone   (TXTcelular.getText());
            obj.setCelular    (TXTcelular.getText());
            obj.setCep        (TXTcep.getText());
            obj.setEndereco   (TXTendereco.getText());
            obj.setNumero     (Integer.parseInt(TXTnumero.getText()));
            obj.setComplemento(TXTcomplemento.getText());
            obj.setBairro     (TXTbairro.getText());
            obj.setCidade     (TXTcidade.getText());
            obj.setUf         (CBOXuf.getSelectedItem().toString());
            
            obj.setId(Integer.parseInt(TXTid.getText()));
            
            FuncionariosDAO dao = new FuncionariosDAO();
            dao.alterarFuncionarios(obj);
            new Utilitarios().limpaTela(PAINELcadastrarfuncionarios);
            
            } catch (Exception e) {
        }
    }//GEN-LAST:event_BalterarActionPerformed

    private void BexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BexcluirActionPerformed
        try {
            
            Funcionarios obj = new Funcionarios();
            
            obj.setId(Integer.parseInt(TXTid.getText()));
            
            FuncionariosDAO dao = new FuncionariosDAO();
            dao.excluirFuncionarios(obj);
            
            new Utilitarios().limpaTela(PAINELcadastrarfuncionarios);
            
            } catch (Exception e) {
        }
    }//GEN-LAST:event_BexcluirActionPerformed

    private void TXTcepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTcepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTcepActionPerformed

    private void TXTcepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTcepKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
         Funcionarios obj =  new Funcionarios();
         FuncionariosDAO dao = new FuncionariosDAO();
            obj = dao.buscaCep(TXTcep.getText());
         
         TXTendereco.setText(obj.getEndereco());
         TXTbairro.setText(obj.getBairro());
         TXTcidade.setText(obj.getCidade());
         CBOXuf.setSelectedItem(obj.getUf());               
         System.out.println(obj.getUf());
         
     }
    }//GEN-LAST:event_TXTcepKeyPressed

    private void BpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpesquisarActionPerformed
       String nome = "%" + TXTpesquisarnome.getText() + "%";
        
FuncionariosDAO dao = new FuncionariosDAO();
        List<Funcionarios> lista = dao.buscaFuncionariosPorNome(nome);
        DefaultTableModel dados = (DefaultTableModel) TABfuncionarios.getModel();
        dados.setNumRows(0);
        
        for (Funcionarios f: lista){
            dados.addRow(new Object[]{
            
                f.getId(),
                f.getNome(),
                f.getRg(),
                f.getCpf(),
                f.getEmail(),
                f.getSenha(),
                f.getCargo(),
                f.getNivel_acesso(),
                f.getTelefone(),
                f.getCelular(),
                f.getCep(),
                f.getEndereco(),
                f.getNumero(),
                f.getComplemento(),
                f.getBairro(),
                f.getCidade(),
                f.getUf(),
        });
        }
    }//GEN-LAST:event_BpesquisarActionPerformed

    private void BbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbuscarActionPerformed
                  
            String nome =TXTnome.getText();
            Funcionarios obj = new Funcionarios();
            FuncionariosDAO dao = new FuncionariosDAO();
            
            obj = dao.consultaPorNome(nome);
            
            if(obj.getNome()!=null){
            
            TXTid.setText(String.valueOf(obj.getId()));
            
            TXTnome.setText(obj.getNome());
            TXTrg.setText(obj.getRg());
            TXTcpf.setText(obj.getCpf());
            TXTlogin.setText(obj.getEmail());
            TXTsenha.setText(obj.getSenha());
            TXTcargo.setText(obj.getCargo());
            CBOXnivel_acesso.setSelectedItem(obj.getNivel_acesso());
            TXTcelular.setText(obj.getTelefone());
            TXTcelular.setText(obj.getCelular());
            TXTcep.setText(obj.getNome());
            TXTendereco.setText(obj.getEndereco());
            TXTnumero.setText(String.valueOf(obj.getNumero()));
            TXTcomplemento.setText(obj.getComplemento());
            TXTbairro.setText(obj.getBairro());
            TXTcidade.setText  (obj.getCidade());
            CBOXuf.setSelectedItem(obj.getUf());
            
        } else {
            JOptionPane.showMessageDialog(null, "Erro: Funcionário Não Encontrado.");
        }
    }//GEN-LAST:event_BbuscarActionPerformed

    private void TXTcelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTcelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTcelularActionPerformed

    private void TXTtelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTtelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTtelefoneActionPerformed

    private void TXTcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTcpfActionPerformed

    private void TXTrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTrgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Balterar;
    private javax.swing.JButton Bbuscar;
    private javax.swing.JButton Bexcluir;
    private javax.swing.JButton Bnovo;
    private javax.swing.JButton Bpesquisar;
    private javax.swing.JButton Bsalvar;
    private javax.swing.JComboBox<String> CBOXnivel_acesso;
    private javax.swing.JComboBox<String> CBOXuf;
    private javax.swing.JLabel LABELbairro;
    private javax.swing.JLabel LABELcargo;
    private javax.swing.JLabel LABELcelular;
    private javax.swing.JLabel LABELcep;
    private javax.swing.JLabel LABELcidade;
    private javax.swing.JLabel LABELcomplemento;
    private javax.swing.JLabel LABELcpf;
    private javax.swing.JLabel LABELemail;
    private javax.swing.JLabel LABELendereco;
    private javax.swing.JLabel LABELenterparaauto;
    private javax.swing.JLabel LABELid;
    private javax.swing.JLabel LABELniveldeacesso;
    private javax.swing.JLabel LABELnome;
    private javax.swing.JLabel LABELnumero;
    private javax.swing.JLabel LABELpesquisarnome;
    private javax.swing.JLabel LABELrg;
    private javax.swing.JLabel LABELsenha;
    private javax.swing.JLabel LABELtelefone;
    private javax.swing.JLabel LABELuf;
    private javax.swing.JLabel Lregistradordeprodutos;
    private javax.swing.JPanel PAINELcadastrarfuncionarios;
    private javax.swing.JPanel PAINELprocurarfuncionarios;
    private javax.swing.JPanel Pregistradordeprodutos;
    private javax.swing.JTable TABfuncionarios;
    private javax.swing.JTextField TXTbairro;
    private javax.swing.JTextField TXTcargo;
    private javax.swing.JFormattedTextField TXTcelular;
    private javax.swing.JTextField TXTcep;
    private javax.swing.JTextField TXTcidade;
    private javax.swing.JTextField TXTcomplemento;
    private javax.swing.JFormattedTextField TXTcpf;
    private javax.swing.JTextField TXTendereco;
    private javax.swing.JTextField TXTid;
    private javax.swing.JTextField TXTlogin;
    private javax.swing.JTextField TXTnome;
    private javax.swing.JTextField TXTnumero;
    private javax.swing.JTextField TXTpesquisarnome;
    private javax.swing.JFormattedTextField TXTrg;
    private javax.swing.JPasswordField TXTsenha;
    private javax.swing.JFormattedTextField TXTtelefone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
