/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.FornecedoresDAO;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Fornecedores;
import model.Utilitarios;

/**
 *
 * @author caio
 */
public class ViewFornecedores extends javax.swing.JFrame {

    /**
     * Creates new form ViewClientes
     */
    
    public void listar(){
        
        FornecedoresDAO dao = new FornecedoresDAO();
        List<Fornecedores> lista = dao.listarFornecedores();
        DefaultTableModel dados = (DefaultTableModel) TABfornecedores.getModel();
        dados.setNumRows(0);
        
        for (Fornecedores c: lista){
            dados.addRow(new Object[]{
            
                c.getId(),
                c.getNome(),
                c.getCnpj(),
                c.getEmail(),
                c.getTelefone(),
                c.getCelular(),
                c.getCep(),
                c.getEndereco(),
                c.getNumero(),
                c.getComplemento(),
                c.getBairro(),
                c.getCidade(),
                c.getUf(),
        });
        }
    }
    
    public ViewFornecedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Pregistradordeprodutos = new javax.swing.JPanel();
        Lregistradordeprodutos = new javax.swing.JLabel();
        Bexcluir = new javax.swing.JButton();
        Bnovo = new javax.swing.JButton();
        Balterar = new javax.swing.JButton();
        Bsalvar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PAINELcadastrarfornecedores = new javax.swing.JPanel();
        LABELid = new javax.swing.JLabel();
        TXTid = new javax.swing.JTextField();
        LABELnome = new javax.swing.JLabel();
        TXTnome = new javax.swing.JTextField();
        LABELemail = new javax.swing.JLabel();
        TXTemail = new javax.swing.JTextField();
        LABELcelular = new javax.swing.JLabel();
        LABELtelefone = new javax.swing.JLabel();
        LABELcep = new javax.swing.JLabel();
        TXTcep = new javax.swing.JTextField();
        LABELendereco = new javax.swing.JLabel();
        TXTendereco = new javax.swing.JTextField();
        LABELnumero = new javax.swing.JLabel();
        TXTnumero = new javax.swing.JTextField();
        LABELcidade = new javax.swing.JLabel();
        TXTcidade = new javax.swing.JTextField();
        LABELbairro = new javax.swing.JLabel();
        TXTbairro = new javax.swing.JTextField();
        LABELcomplemento = new javax.swing.JLabel();
        TXTcomplemento = new javax.swing.JTextField();
        LABELuf = new javax.swing.JLabel();
        CBOXuf = new javax.swing.JComboBox<>();
        LABELcnpj = new javax.swing.JLabel();
        TXTcnpj = new javax.swing.JTextField();
        LABELenterparaauto = new javax.swing.JLabel();
        Bbuscar = new javax.swing.JButton();
        TXTcelular = new javax.swing.JFormattedTextField();
        TXTtelefone = new javax.swing.JFormattedTextField();
        PAINELprocurarfornecedores = new javax.swing.JPanel();
        PAINELfornecedores = new javax.swing.JScrollPane();
        TABfornecedores = new javax.swing.JTable();
        LABELpesquisarnome = new javax.swing.JLabel();
        TXTpesquisarnome = new javax.swing.JTextField();
        Bpesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GERENCIADOR DE FORNECEDORES - SilhuettaSystem");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(236, 230, 230));

        Pregistradordeprodutos.setBackground(new java.awt.Color(102, 102, 102));

        Lregistradordeprodutos.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Lregistradordeprodutos.setForeground(new java.awt.Color(255, 255, 255));
        Lregistradordeprodutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/FORNECEDORESBRANCO.png"))); // NOI18N
        Lregistradordeprodutos.setText("GERENCIADOR   DE   FORNECEDORES");
        Lregistradordeprodutos.setAlignmentX(0.1F);
        Lregistradordeprodutos.setIconTextGap(5);
        Lregistradordeprodutos.setMaximumSize(new java.awt.Dimension(200, 30));
        Lregistradordeprodutos.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout PregistradordeprodutosLayout = new javax.swing.GroupLayout(Pregistradordeprodutos);
        Pregistradordeprodutos.setLayout(PregistradordeprodutosLayout);
        PregistradordeprodutosLayout.setHorizontalGroup(
            PregistradordeprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PregistradordeprodutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lregistradordeprodutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PregistradordeprodutosLayout.setVerticalGroup(
            PregistradordeprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PregistradordeprodutosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Lregistradordeprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Bexcluir.setBackground(new java.awt.Color(227, 227, 227));
        Bexcluir.setForeground(new java.awt.Color(0, 0, 0));
        Bexcluir.setText("Excluir");
        Bexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BexcluirActionPerformed(evt);
            }
        });

        Bnovo.setBackground(new java.awt.Color(227, 227, 227));
        Bnovo.setForeground(new java.awt.Color(0, 0, 0));
        Bnovo.setText("Limpar");
        Bnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnovoActionPerformed(evt);
            }
        });

        Balterar.setBackground(new java.awt.Color(227, 227, 227));
        Balterar.setForeground(new java.awt.Color(0, 0, 0));
        Balterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ALTERAR.png"))); // NOI18N
        Balterar.setText("Editar");
        Balterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalterarActionPerformed(evt);
            }
        });

        Bsalvar.setBackground(new java.awt.Color(227, 227, 227));
        Bsalvar.setForeground(new java.awt.Color(0, 0, 0));
        Bsalvar.setText("Salvar");
        Bsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsalvarActionPerformed(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        PAINELcadastrarfornecedores.setBackground(new java.awt.Color(255, 255, 255));

        LABELid.setForeground(new java.awt.Color(0, 0, 0));
        LABELid.setText("ID:");

        TXTid.setEditable(false);
        TXTid.setBackground(new java.awt.Color(197, 205, 222));
        TXTid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTid.setForeground(new java.awt.Color(0, 0, 0));

        LABELnome.setForeground(new java.awt.Color(0, 0, 0));
        LABELnome.setText("Nome:");

        TXTnome.setBackground(new java.awt.Color(242, 242, 242));
        TXTnome.setForeground(new java.awt.Color(0, 0, 0));

        LABELemail.setForeground(new java.awt.Color(0, 0, 0));
        LABELemail.setText("E-mail:");

        TXTemail.setBackground(new java.awt.Color(242, 242, 242));
        TXTemail.setForeground(new java.awt.Color(0, 0, 0));

        LABELcelular.setForeground(new java.awt.Color(0, 0, 0));
        LABELcelular.setText("Celular:");

        LABELtelefone.setForeground(new java.awt.Color(0, 0, 0));
        LABELtelefone.setText("Telefone (fixo):");

        LABELcep.setForeground(new java.awt.Color(0, 0, 0));
        LABELcep.setText("CEP:");

        TXTcep.setBackground(new java.awt.Color(242, 242, 242));
        TXTcep.setForeground(new java.awt.Color(0, 0, 0));
        TXTcep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTcepActionPerformed(evt);
            }
        });
        TXTcep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTcepKeyPressed(evt);
            }
        });

        LABELendereco.setForeground(new java.awt.Color(0, 0, 0));
        LABELendereco.setText("Endereço:");

        TXTendereco.setBackground(new java.awt.Color(242, 242, 242));
        TXTendereco.setForeground(new java.awt.Color(0, 0, 0));

        LABELnumero.setForeground(new java.awt.Color(0, 0, 0));
        LABELnumero.setText("Nº :");

        TXTnumero.setBackground(new java.awt.Color(242, 242, 242));
        TXTnumero.setForeground(new java.awt.Color(0, 0, 0));

        LABELcidade.setForeground(new java.awt.Color(0, 0, 0));
        LABELcidade.setText("Cidade:");

        TXTcidade.setBackground(new java.awt.Color(242, 242, 242));
        TXTcidade.setForeground(new java.awt.Color(0, 0, 0));

        LABELbairro.setForeground(new java.awt.Color(0, 0, 0));
        LABELbairro.setText("Bairro");

        TXTbairro.setBackground(new java.awt.Color(242, 242, 242));
        TXTbairro.setForeground(new java.awt.Color(0, 0, 0));

        LABELcomplemento.setForeground(new java.awt.Color(0, 0, 0));
        LABELcomplemento.setText("Complemento:");

        TXTcomplemento.setBackground(new java.awt.Color(242, 242, 242));
        TXTcomplemento.setForeground(new java.awt.Color(0, 0, 0));

        LABELuf.setForeground(new java.awt.Color(0, 0, 0));
        LABELuf.setText("UF:");

        CBOXuf.setBackground(new java.awt.Color(242, 242, 242));
        CBOXuf.setForeground(new java.awt.Color(0, 0, 0));
        CBOXuf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        LABELcnpj.setForeground(new java.awt.Color(0, 0, 0));
        LABELcnpj.setText("CNPJ:");

        TXTcnpj.setBackground(new java.awt.Color(242, 242, 242));
        TXTcnpj.setForeground(new java.awt.Color(0, 0, 0));

        LABELenterparaauto.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        LABELenterparaauto.setForeground(new java.awt.Color(0, 0, 0));
        LABELenterparaauto.setText("(ENTER para auto)");

        Bbuscar.setBackground(new java.awt.Color(195, 195, 195));
        Bbuscar.setForeground(new java.awt.Color(0, 0, 0));
        Bbuscar.setText("Buscar");
        Bbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbuscarActionPerformed(evt);
            }
        });

        TXTcelular.setBackground(new java.awt.Color(242, 242, 242));
        TXTcelular.setForeground(new java.awt.Color(0, 0, 0));
        try {
            TXTcelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TXTcelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTcelularActionPerformed(evt);
            }
        });

        TXTtelefone.setBackground(new java.awt.Color(242, 242, 242));
        TXTtelefone.setForeground(new java.awt.Color(0, 0, 0));
        try {
            TXTtelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TXTtelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTtelefoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PAINELcadastrarfornecedoresLayout = new javax.swing.GroupLayout(PAINELcadastrarfornecedores);
        PAINELcadastrarfornecedores.setLayout(PAINELcadastrarfornecedoresLayout);
        PAINELcadastrarfornecedoresLayout.setHorizontalGroup(
            PAINELcadastrarfornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAINELcadastrarfornecedoresLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PAINELcadastrarfornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PAINELcadastrarfornecedoresLayout.createSequentialGroup()
                        .addComponent(LABELcidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PAINELcadastrarfornecedoresLayout.createSequentialGroup()
                        .addComponent(LABELcep)
                        .addGap(18, 18, 18)
                        .addComponent(TXTcep, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LABELenterparaauto))
                    .addGroup(PAINELcadastrarfornecedoresLayout.createSequentialGroup()
                        .addComponent(LABELcomplemento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PAINELcadastrarfornecedoresLayout.createSequentialGroup()
                        .addGroup(PAINELcadastrarfornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LABELemail)
                            .addComponent(LABELid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PAINELcadastrarfornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PAINELcadastrarfornecedoresLayout.createSequentialGroup()
                                .addComponent(TXTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LABELnome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTnome, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bbuscar))
                            .addGroup(PAINELcadastrarfornecedoresLayout.createSequentialGroup()
                                .addGroup(PAINELcadastrarfornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LABELendereco)
                                    .addComponent(LABELbairro)
                                    .addGroup(PAINELcadastrarfornecedoresLayout.createSequentialGroup()
                                        .addComponent(TXTemail, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LABELcelular))
                                    .addComponent(LABELuf))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PAINELcadastrarfornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTendereco)
                                    .addComponent(TXTbairro)
                                    .addGroup(PAINELcadastrarfornecedoresLayout.createSequentialGroup()
                                        .addGroup(PAINELcadastrarfornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PAINELcadastrarfornecedoresLayout.createSequentialGroup()
                                                .addComponent(CBOXuf, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(44, 44, 44)
                                                .addComponent(LABELnumero)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TXTnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PAINELcadastrarfornecedoresLayout.createSequentialGroup()
                                                .addComponent(TXTcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(LABELtelefone)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TXTtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(PAINELcadastrarfornecedoresLayout.createSequentialGroup()
                        .addComponent(LABELcnpj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PAINELcadastrarfornecedoresLayout.setVerticalGroup(
            PAINELcadastrarfornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAINELcadastrarfornecedoresLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PAINELcadastrarfornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELid)
                    .addComponent(TXTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABELnome)
                    .addComponent(TXTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PAINELcadastrarfornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELcelular)
                    .addComponent(LABELemail)
                    .addComponent(TXTemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABELtelefone)
                    .addComponent(TXTcelular)
                    .addComponent(TXTtelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PAINELcadastrarfornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELcep)
                    .addComponent(TXTcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABELendereco)
                    .addComponent(TXTendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABELenterparaauto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PAINELcadastrarfornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELcidade)
                    .addComponent(TXTcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABELbairro)
                    .addComponent(TXTbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PAINELcadastrarfornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PAINELcadastrarfornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LABELnumero)
                        .addComponent(TXTnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PAINELcadastrarfornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LABELuf)
                        .addComponent(LABELcomplemento)
                        .addComponent(TXTcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CBOXuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(105, 105, 105)
                .addGroup(PAINELcadastrarfornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELcnpj)
                    .addComponent(TXTcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar Fornecedor", PAINELcadastrarfornecedores);

        PAINELprocurarfornecedores.setBackground(new java.awt.Color(255, 255, 255));

        TABfornecedores.setBackground(new java.awt.Color(255, 255, 255));
        TABfornecedores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TABfornecedores.setForeground(new java.awt.Color(0, 0, 0));
        TABfornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CNPJ", "E-mail", "Telefone (fixo)", "Celular", "CEP", "Endereço", "Num", "Complemento", "Bairro", "Cidade", "UF"
            }
        ));
        TABfornecedores.setFocusable(false);
        TABfornecedores.setGridColor(new java.awt.Color(204, 204, 204));
        TABfornecedores.setSelectionBackground(new java.awt.Color(0, 0, 0));
        TABfornecedores.setSelectionForeground(new java.awt.Color(255, 255, 255));
        TABfornecedores.setShowGrid(true);
        TABfornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABfornecedoresMouseClicked(evt);
            }
        });
        PAINELfornecedores.setViewportView(TABfornecedores);

        LABELpesquisarnome.setForeground(new java.awt.Color(0, 0, 0));
        LABELpesquisarnome.setText("Nome:");

        TXTpesquisarnome.setBackground(new java.awt.Color(242, 242, 242));

        Bpesquisar.setBackground(new java.awt.Color(195, 195, 195));
        Bpesquisar.setForeground(new java.awt.Color(0, 0, 0));
        Bpesquisar.setText("Atualizar");
        Bpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PAINELprocurarfornecedoresLayout = new javax.swing.GroupLayout(PAINELprocurarfornecedores);
        PAINELprocurarfornecedores.setLayout(PAINELprocurarfornecedoresLayout);
        PAINELprocurarfornecedoresLayout.setHorizontalGroup(
            PAINELprocurarfornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAINELprocurarfornecedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PAINELprocurarfornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PAINELfornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                    .addGroup(PAINELprocurarfornecedoresLayout.createSequentialGroup()
                        .addComponent(LABELpesquisarnome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTpesquisarnome, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bpesquisar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PAINELprocurarfornecedoresLayout.setVerticalGroup(
            PAINELprocurarfornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAINELprocurarfornecedoresLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PAINELprocurarfornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELpesquisarnome)
                    .addComponent(TXTpesquisarnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bpesquisar))
                .addGap(18, 18, 18)
                .addComponent(PAINELfornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Procurar", PAINELprocurarfornecedores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pregistradordeprodutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Bexcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bnovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Balterar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bsalvar)
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Pregistradordeprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bexcluir)
                    .addComponent(Bnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Balterar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bsalvar))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsalvarActionPerformed
        try {
            
            Fornecedores obj = new Fornecedores();
            obj.setNome(TXTnome.getText());
            obj.setCnpj(TXTcnpj.getText());
            obj.setEmail      (TXTemail.getText());
            obj.setTelefone   (TXTtelefone.getText());
            obj.setCelular    (TXTcelular.getText());
            obj.setCep        (TXTcep.getText());
            obj.setEndereco   (TXTendereco.getText());
            obj.setNumero     (Integer.parseInt(TXTnumero.getText()));
            obj.setComplemento(TXTcomplemento.getText());
            obj.setBairro     (TXTbairro.getText());
            obj.setCidade     (TXTcidade.getText());
            obj.setUf         (CBOXuf.getSelectedItem().toString());
            
            FornecedoresDAO dao = new FornecedoresDAO();
            dao.cadastrarFornecedores(obj);
            
            new Utilitarios().limpaTela(PAINELcadastrarfornecedores);
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_BsalvarActionPerformed

    private void BnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnovoActionPerformed
        new Utilitarios().limpaTela(PAINELcadastrarfornecedores);        
    }//GEN-LAST:event_BnovoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void TABfornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABfornecedoresMouseClicked
        jTabbedPane1.setSelectedIndex(0);
        
        TXTid.setText(TABfornecedores.getValueAt(TABfornecedores.getSelectedRow(), 0).toString());
        TXTnome.setText(TABfornecedores.getValueAt(TABfornecedores.getSelectedRow(), 1).toString());
        TXTcnpj.setText(TABfornecedores.getValueAt(TABfornecedores.getSelectedRow(), 2).toString());        
        TXTemail.setText(TABfornecedores.getValueAt(TABfornecedores.getSelectedRow(), 3).toString());
        TXTtelefone.setText(TABfornecedores.getValueAt(TABfornecedores.getSelectedRow(), 4).toString());
        TXTcelular.setText(TABfornecedores.getValueAt  (TABfornecedores.getSelectedRow(), 5).toString());
        TXTcep.setText(TABfornecedores.getValueAt(TABfornecedores.getSelectedRow(), 6).toString());
        TXTendereco.setText(TABfornecedores.getValueAt(TABfornecedores.getSelectedRow(), 7).toString());
        TXTnumero.setText(TABfornecedores.getValueAt(TABfornecedores.getSelectedRow(), 8).toString());
        TXTcomplemento.setText(TABfornecedores.getValueAt(TABfornecedores.getSelectedRow(), 9).toString());
        TXTbairro.setText(TABfornecedores.getValueAt(TABfornecedores.getSelectedRow(), 10).toString());
        TXTcidade.setText(TABfornecedores.getValueAt(TABfornecedores.getSelectedRow(), 11).toString());
        CBOXuf.setSelectedItem(TABfornecedores.getValueAt(TABfornecedores.getSelectedRow(), 12).toString());

    }//GEN-LAST:event_TABfornecedoresMouseClicked

    private void BalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalterarActionPerformed
        try {
            
            Fornecedores obj = new Fornecedores();
            obj.setNome(TXTnome.getText());
            obj.setCnpj(TXTcnpj.getText());
            obj.setEmail      (TXTemail.getText());
            obj.setTelefone   (TXTtelefone.getText());
            obj.setCelular    (TXTcelular.getText());
            obj.setCep        (TXTcep.getText());
            obj.setEndereco   (TXTendereco.getText());
            obj.setNumero     (Integer.parseInt(TXTnumero.getText()));
            obj.setComplemento(TXTcomplemento.getText());
            obj.setBairro     (TXTbairro.getText());
            obj.setCidade     (TXTcidade.getText());
            obj.setUf         (CBOXuf.getSelectedItem().toString());
            
            obj.setId(Integer.parseInt(TXTid.getText()));
            
            FornecedoresDAO dao = new FornecedoresDAO();
            dao.alterarFornecedores(obj);
            
            new Utilitarios().limpaTela(PAINELcadastrarfornecedores);
            
            } catch (Exception e) {
        }
    }//GEN-LAST:event_BalterarActionPerformed

    private void BexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BexcluirActionPerformed
        try {
            
            Fornecedores obj = new Fornecedores();
            
            obj.setId(Integer.parseInt(TXTid.getText()));
            
            FornecedoresDAO dao = new FornecedoresDAO();
            dao.excluirFornecedores(obj);
            
            new Utilitarios().limpaTela(PAINELcadastrarfornecedores);
            
            } catch (Exception e) {
        }
    }//GEN-LAST:event_BexcluirActionPerformed

    private void BpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpesquisarActionPerformed

        String nome = "%" + TXTpesquisarnome.getText() + "%";
        
FornecedoresDAO dao = new FornecedoresDAO();
        List<Fornecedores> lista = dao.buscaFornecedoresPorNome(nome);
        DefaultTableModel dados = (DefaultTableModel) TABfornecedores.getModel();
        dados.setNumRows(0);
        
        for (Fornecedores c: lista){
            dados.addRow(new Object[]{
            
                c.getId(),
                c.getNome(),
                c.getCnpj(),                
                c.getEmail(),
                c.getTelefone(),
                c.getCelular(),
                c.getCep(),
                c.getEndereco(),
                c.getNumero(),
                c.getComplemento(),
                c.getBairro(),
                c.getCidade(),
                c.getUf(),
        });
        }
        
    }//GEN-LAST:event_BpesquisarActionPerformed

    private void TXTcepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTcepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTcepActionPerformed

    private void TXTcepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTcepKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
         Fornecedores obj =  new Fornecedores();
         FornecedoresDAO dao = new FornecedoresDAO();
            obj = dao.buscaCep(TXTcep.getText());
         
         TXTendereco.setText(obj.getEndereco());
         TXTbairro.setText(obj.getBairro());
         TXTcidade.setText(obj.getCidade());
         CBOXuf.setSelectedItem(obj.getUf());               
         System.out.println(obj.getUf());
         
     }
    }//GEN-LAST:event_TXTcepKeyPressed

    private void BbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbuscarActionPerformed
        
            
            String nome =TXTnome.getText();
            Fornecedores obj = new Fornecedores();
            FornecedoresDAO dao = new FornecedoresDAO();
            
            obj = dao.consultaPorNome(nome);
            
            if(obj.getNome()!=null){
            
            TXTid.setText(String.valueOf(obj.getId()));
            
            TXTnome.setText(obj.getNome());
            TXTcnpj.setText(obj.getCnpj());            
            TXTemail.setText(obj.getEmail());
            TXTtelefone.setText(obj.getTelefone());
            TXTcelular.setText(obj.getCelular());
            TXTcep.setText(obj.getCep());
            TXTendereco.setText(obj.getEndereco());
            TXTnumero.setText(String.valueOf(obj.getNumero()));
            TXTcomplemento.setText(obj.getComplemento());
            TXTbairro.setText(obj.getBairro());
            TXTcidade.setText  (obj.getCidade());
            CBOXuf.setSelectedItem(obj.getUf());
            
        } else {
            JOptionPane.showMessageDialog(null, "Erro: Fornecedor Não Encontrado.");
        }
    }//GEN-LAST:event_BbuscarActionPerformed

    private void TXTcelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTcelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTcelularActionPerformed

    private void TXTtelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTtelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTtelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFornecedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Balterar;
    private javax.swing.JButton Bbuscar;
    private javax.swing.JButton Bexcluir;
    private javax.swing.JButton Bnovo;
    private javax.swing.JButton Bpesquisar;
    private javax.swing.JButton Bsalvar;
    private javax.swing.JComboBox<String> CBOXuf;
    private javax.swing.JLabel LABELbairro;
    private javax.swing.JLabel LABELcelular;
    private javax.swing.JLabel LABELcep;
    private javax.swing.JLabel LABELcidade;
    private javax.swing.JLabel LABELcnpj;
    private javax.swing.JLabel LABELcomplemento;
    private javax.swing.JLabel LABELemail;
    private javax.swing.JLabel LABELendereco;
    private javax.swing.JLabel LABELenterparaauto;
    private javax.swing.JLabel LABELid;
    private javax.swing.JLabel LABELnome;
    private javax.swing.JLabel LABELnumero;
    private javax.swing.JLabel LABELpesquisarnome;
    private javax.swing.JLabel LABELtelefone;
    private javax.swing.JLabel LABELuf;
    private javax.swing.JLabel Lregistradordeprodutos;
    private javax.swing.JPanel PAINELcadastrarfornecedores;
    private javax.swing.JScrollPane PAINELfornecedores;
    private javax.swing.JPanel PAINELprocurarfornecedores;
    private javax.swing.JPanel Pregistradordeprodutos;
    private javax.swing.JTable TABfornecedores;
    private javax.swing.JTextField TXTbairro;
    private javax.swing.JFormattedTextField TXTcelular;
    private javax.swing.JTextField TXTcep;
    private javax.swing.JTextField TXTcidade;
    private javax.swing.JTextField TXTcnpj;
    private javax.swing.JTextField TXTcomplemento;
    private javax.swing.JTextField TXTemail;
    private javax.swing.JTextField TXTendereco;
    private javax.swing.JTextField TXTid;
    private javax.swing.JTextField TXTnome;
    private javax.swing.JTextField TXTnumero;
    private javax.swing.JTextField TXTpesquisarnome;
    private javax.swing.JFormattedTextField TXTtelefone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
