/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author caio
 */
public class ViewMenuPrincipal extends javax.swing.JFrame {
    

    /**
     * Creates new form ViewMenuPrincipal
     */
    public ViewMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Bvendas = new javax.swing.JButton();
        Bprodutos = new javax.swing.JButton();
        Bfornecedores = new javax.swing.JButton();
        Bclientes = new javax.swing.JButton();
        Bfuncionarios = new javax.swing.JButton();
        Bconfig = new javax.swing.JButton();
        Bsair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        LABELfundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU PRINCIPAL - SilhuettaSystem");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(174, 144, 84));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logo-Sullhueta-BRANCO.png"))); // NOI18N

        Bvendas.setBackground(new java.awt.Color(174, 144, 84));
        Bvendas.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Bvendas.setForeground(new java.awt.Color(255, 255, 255));
        Bvendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/VENDASBRANCO.png"))); // NOI18N
        Bvendas.setText("VENDAS");
        Bvendas.setBorderPainted(false);
        Bvendas.setContentAreaFilled(false);
        Bvendas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Bvendas.setHideActionText(true);
        Bvendas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Bvendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BvendasActionPerformed(evt);
            }
        });

        Bprodutos.setBackground(new java.awt.Color(174, 144, 84));
        Bprodutos.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Bprodutos.setForeground(new java.awt.Color(255, 255, 255));
        Bprodutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/PRODUTOSBRANCO.png"))); // NOI18N
        Bprodutos.setText("PRODUTOS");
        Bprodutos.setBorderPainted(false);
        Bprodutos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Bprodutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BprodutosActionPerformed(evt);
            }
        });

        Bfornecedores.setBackground(new java.awt.Color(174, 144, 84));
        Bfornecedores.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Bfornecedores.setForeground(new java.awt.Color(255, 255, 255));
        Bfornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/FORNECEDORESBRANCO.png"))); // NOI18N
        Bfornecedores.setText("FORNECEDORES");
        Bfornecedores.setBorderPainted(false);
        Bfornecedores.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Bfornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BfornecedoresActionPerformed(evt);
            }
        });

        Bclientes.setBackground(new java.awt.Color(174, 144, 84));
        Bclientes.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Bclientes.setForeground(new java.awt.Color(255, 255, 255));
        Bclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/CLIENTESB.png"))); // NOI18N
        Bclientes.setText("CLIENTES");
        Bclientes.setBorderPainted(false);
        Bclientes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Bclientes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Bclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BclientesActionPerformed(evt);
            }
        });

        Bfuncionarios.setBackground(new java.awt.Color(174, 144, 84));
        Bfuncionarios.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Bfuncionarios.setForeground(new java.awt.Color(255, 255, 255));
        Bfuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/FUNCIONARIOS BRANCO.png"))); // NOI18N
        Bfuncionarios.setText("FUNCIONÁRIOS");
        Bfuncionarios.setBorderPainted(false);
        Bfuncionarios.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Bfuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BfuncionariosActionPerformed(evt);
            }
        });

        Bconfig.setBackground(new java.awt.Color(174, 144, 84));
        Bconfig.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Bconfig.setForeground(new java.awt.Color(255, 255, 255));
        Bconfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/CONFIGBRANCO.png"))); // NOI18N
        Bconfig.setText("USUÁRIO");
        Bconfig.setBorderPainted(false);
        Bconfig.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Bconfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BconfigActionPerformed(evt);
            }
        });

        Bsair.setBackground(new java.awt.Color(174, 144, 84));
        Bsair.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Bsair.setForeground(new java.awt.Color(255, 255, 255));
        Bsair.setText("SAIR");
        Bsair.setBorderPainted(false);
        Bsair.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Bsair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BsairMouseClicked(evt);
            }
        });
        Bsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsairActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(236, 230, 230));

        LABELfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fundo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LABELfundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LABELfundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bvendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bprodutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bfornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bclientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bfuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bconfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bsair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Bvendas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bfornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bfuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bconfig, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(Bsair, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 91, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 445, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BfuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BfuncionariosActionPerformed
        ViewFuncionarios tela = new ViewFuncionarios();
        tela.setVisible(true);
    }//GEN-LAST:event_BfuncionariosActionPerformed

    private void BvendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BvendasActionPerformed
        ViewVendas tela = new ViewVendas();
        tela.setVisible(true);
    }//GEN-LAST:event_BvendasActionPerformed

    private void BprodutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BprodutosActionPerformed
        ViewProdutos tela = new ViewProdutos();
        tela.setVisible(true);
    }//GEN-LAST:event_BprodutosActionPerformed

    private void BfornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BfornecedoresActionPerformed
        ViewFornecedores tela = new ViewFornecedores();
        tela.setVisible(true);
    }//GEN-LAST:event_BfornecedoresActionPerformed

    private void BclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BclientesActionPerformed
        ViewClientes tela = new ViewClientes();
        tela.setVisible(true);
    }//GEN-LAST:event_BclientesActionPerformed

    private void BsairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BsairMouseClicked
        int op;
        op = JOptionPane.showConfirmDialog(null,"Tem certeza que deseja sair?");
        if(op == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_BsairMouseClicked

    private void BconfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BconfigActionPerformed
        ViewLogin tela = new ViewLogin();
        tela.setVisible(true);
    }//GEN-LAST:event_BconfigActionPerformed

    private void BsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BsairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenuPrincipal().setVisible(true);                
            }                                 
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bclientes;
    private javax.swing.JButton Bconfig;
    private javax.swing.JButton Bfornecedores;
    private javax.swing.JButton Bfuncionarios;
    private javax.swing.JButton Bprodutos;
    private javax.swing.JButton Bsair;
    private javax.swing.JButton Bvendas;
    private javax.swing.JLabel LABELfundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
