/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ProdutosDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Produtos;

/**
 *
 * @author caio
 */
public class ViewEstoque extends javax.swing.JFrame {
    int idproduto;
    int qnt_nova;
    /**
     * Creates new form ViewEstoque
     */
    public void listar(){
        
        ProdutosDAO dao = new ProdutosDAO();
        List<Produtos> lista = dao.listarProdutos();
        DefaultTableModel dados = (DefaultTableModel) TABprodutos.getModel();
        dados.setNumRows(0);
        
        for (Produtos p: lista){
            dados.addRow(new Object[]{
            
                p.getCodigo(),        
                p.getReferencia(),
                p.getCusto(),
                p.getQuantidade(),
                p.getFornecedor(),
                p.getModelo(),
                p.getTipo(),
                p.getTamanho(),
                p.getCor(),
                        
        });
        }
    }
    public ViewEstoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Pregistradordeprodutos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TXTestoque = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TXTadicionar = new javax.swing.JTextField();
        PAINELprodutos = new javax.swing.JScrollPane();
        TABprodutos = new javax.swing.JTable();
        Badicionar = new javax.swing.JButton();
        LABELpesquisarref = new javax.swing.JLabel();
        TXTpesquisarref = new javax.swing.JTextField();
        Batualizarref = new javax.swing.JButton();
        LABELpesquisarref1 = new javax.swing.JLabel();
        TXTpesquisarmod = new javax.swing.JTextField();
        LABELpesquisarref2 = new javax.swing.JLabel();
        TXTpesquisartam = new javax.swing.JTextField();
        TXTpesquisarcor = new javax.swing.JTextField();
        LABELpesquisarref3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONTROLE DE ESTOQUE - SilhuettaSystem");
        setPreferredSize(new java.awt.Dimension(867, 554));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(236, 230, 230));
        jPanel1.setPreferredSize(new java.awt.Dimension(867, 554));

        Pregistradordeprodutos.setBackground(new java.awt.Color(174, 144, 84));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logo-Sullhueta-BRANCO.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ESTOQUE BRANCO.png"))); // NOI18N
        jLabel2.setText("CONTROLE DE ESTOQUE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PregistradordeprodutosLayout = new javax.swing.GroupLayout(Pregistradordeprodutos);
        Pregistradordeprodutos.setLayout(PregistradordeprodutosLayout);
        PregistradordeprodutosLayout.setHorizontalGroup(
            PregistradordeprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PregistradordeprodutosLayout.setVerticalGroup(
            PregistradordeprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PregistradordeprodutosLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Estoque Atual:");

        TXTestoque.setEditable(false);
        TXTestoque.setBackground(new java.awt.Color(197, 205, 222));
        TXTestoque.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Adicionar ao Estoque:");

        TXTadicionar.setBackground(new java.awt.Color(255, 255, 255));
        TXTadicionar.setForeground(new java.awt.Color(0, 0, 0));

        TABprodutos.setBackground(new java.awt.Color(255, 255, 255));
        TABprodutos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TABprodutos.setForeground(new java.awt.Color(0, 0, 0));
        TABprodutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Código", "Referência", "Custo", "Quantidade", "Fornecedor", "Modelo", "Tipo", "Tamanho", "Cor"
            }
        ));
        TABprodutos.setFocusable(false);
        TABprodutos.setGridColor(new java.awt.Color(204, 204, 204));
        TABprodutos.setSelectionBackground(new java.awt.Color(0, 0, 0));
        TABprodutos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        TABprodutos.setShowGrid(true);
        TABprodutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABprodutosMouseClicked(evt);
            }
        });
        PAINELprodutos.setViewportView(TABprodutos);

        Badicionar.setBackground(new java.awt.Color(195, 195, 195));
        Badicionar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Badicionar.setForeground(new java.awt.Color(0, 0, 102));
        Badicionar.setText("Adicionar");
        Badicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BadicionarActionPerformed(evt);
            }
        });

        LABELpesquisarref.setForeground(new java.awt.Color(0, 0, 0));
        LABELpesquisarref.setText("Referência:");

        TXTpesquisarref.setBackground(new java.awt.Color(255, 255, 255));
        TXTpesquisarref.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTpesquisarrefKeyPressed(evt);
            }
        });

        Batualizarref.setBackground(new java.awt.Color(195, 195, 195));
        Batualizarref.setForeground(new java.awt.Color(0, 0, 0));
        Batualizarref.setText("Atualizar");
        Batualizarref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatualizarrefActionPerformed(evt);
            }
        });

        LABELpesquisarref1.setForeground(new java.awt.Color(0, 0, 0));
        LABELpesquisarref1.setText("Modelo:");

        TXTpesquisarmod.setBackground(new java.awt.Color(255, 255, 255));
        TXTpesquisarmod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTpesquisarmodKeyPressed(evt);
            }
        });

        LABELpesquisarref2.setForeground(new java.awt.Color(0, 0, 0));
        LABELpesquisarref2.setText("Tamanho:");

        TXTpesquisartam.setBackground(new java.awt.Color(255, 255, 255));
        TXTpesquisartam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTpesquisartamKeyPressed(evt);
            }
        });

        TXTpesquisarcor.setBackground(new java.awt.Color(255, 255, 255));
        TXTpesquisarcor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTpesquisarcorKeyPressed(evt);
            }
        });

        LABELpesquisarref3.setForeground(new java.awt.Color(0, 0, 0));
        LABELpesquisarref3.setText("Cor:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pregistradordeprodutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PAINELprodutos, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LABELpesquisarref)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTpesquisarref, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Batualizarref))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(LABELpesquisarref1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LABELpesquisarref2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTpesquisartam, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TXTpesquisarmod)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TXTestoque, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel5)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TXTadicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Badicionar))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(LABELpesquisarref3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TXTpesquisarcor, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Pregistradordeprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELpesquisarref)
                    .addComponent(TXTpesquisarref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Batualizarref))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELpesquisarref1)
                    .addComponent(TXTpesquisarmod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABELpesquisarref3)
                    .addComponent(TXTpesquisarcor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELpesquisarref2)
                    .addComponent(TXTpesquisartam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TXTestoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(TXTadicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Badicionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PAINELprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TABprodutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABprodutosMouseClicked
        idproduto = Integer.parseInt((TABprodutos.getValueAt(TABprodutos.getSelectedRow(), 0).toString()));
        TXTpesquisarref.setText  (TABprodutos.getValueAt(TABprodutos.getSelectedRow(), 2).toString());
        
        TXTestoque.setText(TABprodutos.getValueAt(TABprodutos.getSelectedRow(), 4).toString());

    }//GEN-LAST:event_TABprodutosMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void BadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BadicionarActionPerformed
        try {
            int estoque = Integer.parseInt(TXTestoque.getText());
            qnt_nova = Integer.parseInt(TXTadicionar.getText());
            int qnt_atualizada = estoque+qnt_nova;
            ProdutosDAO dao = new ProdutosDAO();
            
            dao.baixaEstoque(idproduto, qnt_atualizada);
            
            JOptionPane.showMessageDialog(null, "Estoque atualizado com SUCESSO.");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Botão Adicionar Erro: " + e);
        }
    }//GEN-LAST:event_BadicionarActionPerformed

    private void TXTpesquisarrefKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTpesquisarrefKeyPressed

    }//GEN-LAST:event_TXTpesquisarrefKeyPressed

    private void BatualizarrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatualizarrefActionPerformed

        String referencia = "%" + TXTpesquisarref.getText() + "%";
        String modelo = "%" + TXTpesquisarmod.getText() + "%";
        String tamanho = "%" + TXTpesquisartam.getText() + "%";
        String cor = "%" + TXTpesquisarcor.getText() + "%";

        ProdutosDAO dao = new ProdutosDAO();
        List<Produtos> lista = dao.buscaProdutosPorFiltro(referencia,modelo,tamanho,cor);
        DefaultTableModel dados = (DefaultTableModel) TABprodutos.getModel();
        dados.setNumRows(0);

        for (Produtos p: lista){
            dados.addRow(new Object[]{
                p.getId(),
                p.getCodigo(),
                p.getReferencia(),
                p.getCusto(),
                p.getQuantidade(),
                p.getFornecedor(),
                p.getModelo(),
                p.getTipo(),
                p.getTamanho(),
                p.getCor(),

            });
        }

    }//GEN-LAST:event_BatualizarrefActionPerformed

    private void TXTpesquisarmodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTpesquisarmodKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTpesquisarmodKeyPressed

    private void TXTpesquisartamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTpesquisartamKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTpesquisartamKeyPressed

    private void TXTpesquisarcorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTpesquisarcorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTpesquisarcorKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Badicionar;
    private javax.swing.JButton Batualizarref;
    private javax.swing.JLabel LABELpesquisarref;
    private javax.swing.JLabel LABELpesquisarref1;
    private javax.swing.JLabel LABELpesquisarref2;
    private javax.swing.JLabel LABELpesquisarref3;
    private javax.swing.JScrollPane PAINELprodutos;
    private javax.swing.JPanel Pregistradordeprodutos;
    private javax.swing.JTable TABprodutos;
    private javax.swing.JTextField TXTadicionar;
    private javax.swing.JTextField TXTestoque;
    private javax.swing.JTextField TXTpesquisarcor;
    private javax.swing.JTextField TXTpesquisarmod;
    private javax.swing.JTextField TXTpesquisarref;
    private javax.swing.JTextField TXTpesquisartam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
